## 1.1 Data in the 21st Century

## 1.2 Introducing pandas



### 1.2.1 Pandas vs. Graphical Spreadsheet Applications

 pandas와 excel은 process가 동일하다. -> 사용할 올바른 함수를 식별하고 올바른 순서로 올바른 입력값을 입력하는 것은 pandas에도 적용되는 원리이다.
 Graphical Spreadsheet Applications(예: excel)은 dataset의 크기에 따른 제한을 받는다(excel은 약 1048576행의 data로 제한된다.). 하지만 pandas는 큰 dataset도 처리할 수 있기에 excel보다 활용성이 높다. pandas의 제한 사항은 오직 컴퓨터 메모리 크기와 처리 능력이다.
 Graphical Spreadsheet Applications은 주로 작은 dataset을 처리할 때 사용하면 유용하고, pandas는 아주 큰 dataset을 처리할 때 유용하다.

### 1.2.2 Pandas vs. Its Competitors

programming language R은 통계에 특화된 언어이지만 python은 그보다는 범용적인 언어이다. 서로 경쟁하는 언어가 아닌 함께 사용되는 언어이다.
SQL은 Database관리를 위한 언어이고, pandas는 데이터 분석을 위해 구축된 library이다. 이 두 개 또한 서로 경쟁하는 것이 아닌 서로를 보완하는 역할을 한다.
SQL을 사용하여 데이터의 초기 클러스터를 추출한 다음 pandas를 사용하여 data를 조작한다.

## 1.3 A Tour of Pandas

### 1.3.1 Importing a Data Set

In [2]:
import pandas as pd

CSV(comma-separated values)파일은 data의 각 행을 줄 바꿈으로 구분하고 각 행의 값을 쉼표로 구분하는 "일반 텍스트 파일"이다.
이러한 파일의 첫 번째 행에는 data의 column header가 있다.

예:

    Rank,Title,Studio,Gross,Year
    1,Avengers: Endgame,Buena Vista, "$2,796.30",2019
2,Avatar,Fox,"$2,789.70",2009

In [3]:
pd.read_csv("movies.csv")

     Rank                         Title           Studio       Gross  Year
0       1             Avengers: Endgame      Buena Vista  $2,796.30   2019
1       2                        Avatar              Fox  $2,789.70   2009
2       3                       Titanic        Paramount  $2,187.50   1997
3       4  Star Wars: The Force Awakens      Buena Vista  $2,068.20   2015
4       5        Avengers: Infinity War      Buena Vista  $2,048.40   2018
..    ...                           ...              ...         ...   ...
777   778                     Yogi Bear  Warner Brothers    $201.60   2010
778   779           Garfield: The Movie              Fox    $200.80   2004
779   780                   Cats & Dogs  Warner Brothers    $200.70   2001
780   781      The Hunt for Red October        Paramount    $200.50   1990
781   782                      Valkyrie              MGM    $200.30   2008

[782 rows x 5 columns]

pandas는 CSV파일의 내용을 DataFrame라는 object로 가져온다.

DataFrame의 index label은 data 행의 식별자 역할을 한다. 모든 column을 DataFrame의 index로 설정할 수 있다.

index에 적합한 column은 각 행에 대한 기본 식별자 혹은 참조 지점으로 사용할 수 있는 값에 대한 column이다.

다음 코드에서는 Title에 대한 column을 각 행의 index label로 설정하였다.

In [4]:
pd.read_csv("movies.csv", index_col = "Title")

                              Rank           Studio       Gross  Year
Title
Avengers: Endgame                1      Buena Vista  $2,796.30   2019
Avatar                           2              Fox  $2,789.70   2009
Titanic                          3        Paramount  $2,187.50   1997
Star Wars: The Force Awakens     4      Buena Vista  $2,068.20   2015
Avengers: Infinity War           5      Buena Vista  $2,048.40   2018
...                            ...              ...         ...   ...
Yogi Bear                      778  Warner Brothers    $201.60   2010
Garfield: The Movie            779              Fox    $200.80   2004
Cats & Dogs                    780  Warner Brothers    $200.70   2001
The Hunt for Red October       781        Paramount    $200.50   1990
Valkyrie                       782              MGM    $200.30   2008

[782 rows x 4 columns]

In [5]:
movies = pd.read_csv("movies.csv", index_col = "Title")

### 1.3.2 Manipulating a DataFrame

In [6]:
#4행까지 추출
movies.head(4)

                              Rank       Studio       Gross  Year
Title
Avengers: Endgame                1  Buena Vista  $2,796.30   2019
Avatar                           2          Fox  $2,789.70   2009
Titanic                          3    Paramount  $2,187.50   1997
Star Wars: The Force Awakens     4  Buena Vista  $2,068.20   2015

In [7]:
#마지막 6행 추출
movies.tail(6)

                          Rank           Studio     Gross  Year
Title
21 Jump Street             777             Sony  $201.60   2012
Yogi Bear                  778  Warner Brothers  $201.60   2010
Garfield: The Movie        779              Fox  $200.80   2004
Cats & Dogs                780  Warner Brothers  $200.70   2001
The Hunt for Red October   781        Paramount  $200.50   1990
Valkyrie                   782              MGM  $200.30   2008

In [8]:
#DataFrame내 행 개수 확인
len(movies)

782

In [9]:
#DataFrame의 행과 열 개수 확인
movies.shape

(782, 4)

In [10]:
#총 셀의 개수 확인 이때는 782*4=3128개가 있다.
movies.size

3128

In [11]:
#Dataframe내 각 column의 data type을 확인
#이때 object는 text column을 나타낸다.
movies.dtypes

Rank       int64
Studio    object
Gross     object
Year       int64
dtype: object

In [12]:
#행의 숫자 순서로 DataFrame에서 행을 추출
#다은은 500번째 행을 추출하였다.
print(movies.iloc[499])
print("\n\n")
print(type(movies.iloc[499]))

Rank           500
Studio         Fox
Gross     $288.30
Year          2018
Name: Maze Runner: The Death Cure, dtype: object



<class 'pandas.core.series.Series'>

위와 같이 pandas는 1차원 label이 지정된 값 배열인 Series object을 반환한다.

이 Series는 각 행에 대한 식별자(Series의 index label)가 있는 단일 data column이라 생각하면 된다.

In [13]:
#index label로 DataFrame행에 접근할 수도 있다.
movies.loc["Forrest Gump"]

Rank            119
Studio    Paramount
Gross      $677.90
Year           1994
Name: Forrest Gump, dtype: object

In [14]:
#index label(이 경우 Title)이 중복된 경우 다음과 같이 DataFrame으로 추출한다.
print(movies.loc["101 Dalmatians"])
print("\n\n")
print(type(movies.loc["101 Dalmatians"]))

                Rank       Studio     Gross  Year
Title
101 Dalmatians   425  Buena Vista  $320.70   1996
101 Dalmatians   708  Buena Vista  $215.90   1961



<class 'pandas.core.frame.DataFrame'>

In [15]:
#DataFrame을 Year라는 column의 값으로 정렬시킨다.
#이때 ascending이 True라면 오름차순으로 정렬, False라면 내림차순으로 정렬된다.
movies.sort_values(by = "Year", ascending = False).head()

,Rank,Studio,Gross,Year
Title,,,,
Avengers: Endgame,1,Buena Vista,"$2,796.30",2019
John Wick: Chapter 3 - Parabellum,458,Lionsgate,$304.70,2019
The Wandering Earth,114,China Film Corporation,$699.80,2019
Toy Story 4,198,Buena Vista,$519.80,2019
How to Train Your Dragon: The Hidden World,199,Universal,$519.80,2019

In [16]:
#여러 column 값을 기준으로 DataFrame을 정렬할 수 있다.
#Studio라는 column 값을 기준으로 영화를 정렬한 다음(내림차순 혹은 오름차순) Year라는 column 값을 기준으로 정렬(내림차순 혹은 오름차순)할 수 있다.
movies.sort_values(by = ["Studio", "Year"],ascending=False)

                         Rank       Studio     Gross  Year
Title
The Imitation Game        642    Weinstein  $233.60   2014
The Intouchables          265    Weinstein  $426.60   2012
Django Unchained          266    Weinstein  $425.40   2012
Silver Linings Playbook   631    Weinstein  $236.40   2012
The King's Speech         276    Weinstein  $414.20   2010
...                       ...          ...       ...   ...
The Little Mermaid        738  Buena Vista  $211.30   1989
Who Framed Roger Rabbit   410  Buena Vista  $329.80   1988
The Jungle Book           755  Buena Vista  $205.80   1967
101 Dalmatians            708  Buena Vista  $215.90   1961
The Blair Witch Project   588      Artisan  $248.60   1999

[782 rows x 4 columns]

In [17]:
movies.sort_values(by="Title",ascending=True)

                                Rank           Studio       Gross  Year
Title
10,000 B.C.                      536  Warner Brothers    $269.80   2008
101 Dalmatians                   708      Buena Vista    $215.90   1961
101 Dalmatians                   425      Buena Vista    $320.70   1996
2 Fast 2 Furious                 632        Universal    $236.40   2003
2012                              93             Sony    $769.70   2009
...                              ...              ...         ...   ...
Yogi Bear                        778  Warner Brothers    $201.60   2010
You've Got Mail                  582  Warner Brothers    $250.80   1998
Your Name.                       356              FUN    $358.00   2017
Zootopia                          37      Buena Vista  $1,023.80   2016
xXx: The Return of Xander Cage   385        Paramount    $346.10   2017

[782 rows x 4 columns]

index를 정렬할 때 위와 같이 정렬해도 되고, 아래와 같이 정렬해도 된다.

index label이 Title이기 때문에 둘 다 Title을 알파벳 순으로 정렬한 결과가 나온다.

In [18]:
movies.sort_index()

                                Rank           Studio       Gross  Year
Title
10,000 B.C.                      536  Warner Brothers    $269.80   2008
101 Dalmatians                   708      Buena Vista    $215.90   1961
101 Dalmatians                   425      Buena Vista    $320.70   1996
2 Fast 2 Furious                 632        Universal    $236.40   2003
2012                              93             Sony    $769.70   2009
...                              ...              ...         ...   ...
Yogi Bear                        778  Warner Brothers    $201.60   2010
You've Got Mail                  582  Warner Brothers    $250.80   1998
Your Name.                       356              FUN    $358.00   2017
Zootopia                          37      Buena Vista  $1,023.80   2016
xXx: The Return of Xander Cage   385        Paramount    $346.10   2017

[782 rows x 4 columns]

### 1.3.3 Counting Values in a Series

In [19]:
#영화 제목이 index이고 이에 대응하는 값이 Studio인 Series을 추출하였다.
movies["Studio"]

Title
Avengers: Endgame                   Buena Vista
Avatar                                      Fox
Titanic                               Paramount
Star Wars: The Force Awakens        Buena Vista
Avengers: Infinity War              Buena Vista
                                     ...
Yogi Bear                       Warner Brothers
Garfield: The Movie                         Fox
Cats & Dogs                     Warner Brothers
The Hunt for Red October              Paramount
Valkyrie                                    MGM
Name: Studio, Length: 782, dtype: object

In [20]:
#각 Studio값에 대한 Series내에서의 빈도수를 추출한다.
#Studio가 index label로 사용되고, 빈도 수가 값으로 사용되는 Series을 출력한다.
s_counts=movies["Studio"].value_counts().head(10)
print(type(s_counts))
s_counts

<class 'pandas.core.series.Series'>

Studio
Warner Brothers    132
Buena Vista        125
Fox                117
Universal          109
Sony                86
Paramount           76
Dreamworks          27
Lionsgate           21
New Line            16
MGM                 11
Name: count, dtype: int64

### 1.3.4	Filtering a Column by One or More Criteria

In [21]:
#Universal에서 제작된 영화만 추출(DataFrame형식)
movies[movies["Studio"] == "Universal"]

                                Rank     Studio       Gross  Year
Title
Jurassic World                     6  Universal  $1,671.70   2015
Furious 7                          8  Universal  $1,516.00   2015
Jurassic World: Fallen Kingdom    13  Universal  $1,309.50   2018
The Fate of the Furious           17  Universal  $1,236.00   2017
Minions                           19  Universal  $1,159.40   2015
...                              ...        ...         ...   ...
The Break-Up                     763  Universal    $205.00   2006
Everest                          766  Universal    $203.40   2015
Patch Adams                      772  Universal    $202.30   1998
Kindergarten Cop                 775  Universal    $202.00   1990
Straight Outta Compton           776  Universal    $201.60   2015

[109 rows x 4 columns]

In [22]:
released_by_universal = (movies["Studio"] == "Universal")
movies[released_by_universal].head()

                                Rank     Studio       Gross  Year
Title
Jurassic World                     6  Universal  $1,671.70   2015
Furious 7                          8  Universal  $1,516.00   2015
Jurassic World: Fallen Kingdom    13  Universal  $1,309.50   2018
The Fate of the Furious           17  Universal  $1,236.00   2017
Minions                           19  Universal  $1,159.40   2015

In [23]:
#여러 기준으로 DataFrame행을 filtering할 수도 있다.
#다음은 universal에서 제작되고, 2015년도에 개봉한 영화를 추출한다.
released_by_universal = movies["Studio"] == "Universal"
released_in_2015 = movies["Year"] == 2015
movies[released_by_universal & released_in_2015]

                        Rank     Studio       Gross  Year
Title
Jurassic World             6  Universal  $1,671.70   2015
Furious 7                  8  Universal  $1,516.00   2015
Minions                   19  Universal  $1,159.40   2015
Fifty Shades of Grey     165  Universal    $571.00   2015
Pitch Perfect 2          504  Universal    $287.50   2015
Ted 2                    702  Universal    $216.70   2015
Everest                  766  Universal    $203.40   2015
Straight Outta Compton   776  Universal    $201.60   2015

In [24]:
#다음은 universal에서 제작되었거나, 2015년도에 개봉한 영화를 추출한다.
released_by_universal = movies["Studio"] == "Universal"
released_in_2015 = movies["Year"] == 2015
movies[released_by_universal | released_in_2015]

                                Rank       Studio       Gross  Year
Title
Star Wars: The Force Awakens       4  Buena Vista  $2,068.20   2015
Jurassic World                     6    Universal  $1,671.70   2015
Furious 7                          8    Universal  $1,516.00   2015
Avengers: Age of Ultron            9  Buena Vista  $1,405.40   2015
Jurassic World: Fallen Kingdom    13    Universal  $1,309.50   2018
...                              ...          ...         ...   ...
The Break-Up                     763    Universal    $205.00   2006
Everest                          766    Universal    $203.40   2015
Patch Adams                      772    Universal    $202.30   1998
Kindergarten Cop                 775    Universal    $202.00   1990
Straight Outta Compton           776    Universal    $201.60   2015

[140 rows x 4 columns]

In [25]:
before_1975 = movies["Year"] < 1975
movies[before_1975]

                    Rank           Studio     Gross  Year
Title
The Exorcist         252  Warner Brothers  $441.30   1973
Gone with the Wind   288              MGM  $402.40   1939
Bambi                540              RKO  $267.40   1942
The Godfather        604        Paramount  $245.10   1972
101 Dalmatians       708      Buena Vista  $215.90   1961
The Jungle Book      755      Buena Vista  $205.80   1967

In [26]:
#1983년에서 1986년 사이에 개봉한 영화를 filtering
mid_80s = movies["Year"].between(1983, 1986)
movies[mid_80s]

                                      Rank     Studio     Gross  Year
Title
Return of the Jedi                     222        Fox  $475.10   1983
Back to the Future                     311  Universal  $381.10   1985
Top Gun                                357  Paramount  $356.80   1986
Indiana Jones and the Temple of Doom   403  Paramount  $333.10   1984
Crocodile Dundee                       413  Paramount  $328.20   1986
Beverly Hills Cop                      432  Paramount  $316.40   1984
Rocky IV                               467        MGM  $300.50   1985
Rambo: First Blood Part II             469    TriStar  $300.40   1985
Ghostbusters                           485   Columbia  $295.20   1984
Out of Africa                          662  Universal  $227.50   1985

In [27]:
#DataFrame의 index을 소문자로 바꾸고, index 중에서 dark가 포함된 모든 영화를 추출한다.
has_dark_in_title = movies.index.str.lower().str.contains("dark")
movies[has_dark_in_title]

                                Rank           Studio       Gross  Year
Title
Transformers: Dark of the Moon    23        Paramount  $1,123.80   2011
The Dark Knight Rises             27  Warner Brothers  $1,084.90   2012
The Dark Knight                   39  Warner Brothers  $1,004.90   2008
Thor: The Dark World             132      Buena Vista    $644.60   2013
Star Trek Into Darkness          232        Paramount    $467.40   2013
Fifty Shades Darker              309        Universal    $381.50   2017
Dark Shadows                     600  Warner Brothers    $245.50   2012
Dark Phoenix                     603              Fox    $245.10   2019

### 1.3.5 Grouping Data

In [28]:
#기호 $과 ,을 모두 빈 텍스트로 바꾼다.
movies["Gross"].str.replace(
    "$", "", regex = False  #$를 ""로 바꾼다는 의미이다.
).str.replace(",", "", regex = False)

Title
Avengers: Endgame               2796.30
Avatar                          2789.70
Titanic                         2187.50
Star Wars: The Force Awakens    2068.20
Avengers: Infinity War          2048.40
                                  ...
Yogi Bear                        201.60
Garfield: The Movie              200.80
Cats & Dogs                      200.70
The Hunt for Red October         200.50
Valkyrie                         200.30
Name: Gross, Length: 782, dtype: object

In [34]:
#밑의 괄호는 별거 아니다.
#movies["Gross"].str.replace("$", "", regex = False).str.replace(",", "", regex = False).astype(float)
#와 같이 쓸 수 있는 것을 보기 편하게 쓰기 위해서 괄호를 활용한 것이다.
(
    movies["Gross"]
    .str.replace("$", "", regex = False)
    .str.replace(",", "", regex = False)
    .astype(float)
)

Title
Avengers: Endgame               2796.3
Avatar                          2789.7
Titanic                         2187.5
Star Wars: The Force Awakens    2068.2
Avengers: Infinity War          2048.4
                                 ...
Yogi Bear                        201.6
Garfield: The Movie              200.8
Cats & Dogs                      200.7
The Hunt for Red October         200.5
Valkyrie                         200.3
Name: Gross, Length: 782, dtype: float64

In [35]:
#float64형으로 타입을 변형한 것을 원본에다가 덮어씌운다.
movies["Gross"] = (
    movies["Gross"]
    .str.replace("$", "", regex = False)
    .str.replace(",", "", regex = False)
    .astype(float)
)

In [36]:
movies["Gross"].mean()

np.float64(439.0308184143222)

In [57]:
#Studio column의 값을 기반으로 DataFrame의 행을 그룹화한다.
#즉 같은 제작사가 만든 영화를 하나의 그룹으로 만든다는 것이다.
studios = movies.groupby("Studio")

groupby()는 테이블을 다시 그룹으로 묶어서 정렬하여 새로운 테이블을 만들지는 않는다.

단지 어떤 Studio에 어떤 행들이 속하는지에 대한 매핑정보만 내부적으로 들고 있는 객체인 DataFrameGroupBy를 만들 뿐이다.

그렇기에 studios.head()로 보는 테이블은 movies로 보는 테이블과 완전히 같다.

In [52]:
movies

                              Rank           Studio   Gross  Year
Title
Avengers: Endgame                1      Buena Vista  2796.3  2019
Avatar                           2              Fox  2789.7  2009
Titanic                          3        Paramount  2187.5  1997
Star Wars: The Force Awakens     4      Buena Vista  2068.2  2015
Avengers: Infinity War           5      Buena Vista  2048.4  2018
...                            ...              ...     ...   ...
Yogi Bear                      778  Warner Brothers   201.6  2010
Garfield: The Movie            779              Fox   200.8  2004
Cats & Dogs                    780  Warner Brothers   200.7  2001
The Hunt for Red October       781        Paramount   200.5  1990
Valkyrie                       782              MGM   200.3  2008

[782 rows x 4 columns]

In [50]:
studios.head()

                              Rank       Studio   Gross  Year
Title
Avengers: Endgame                1  Buena Vista  2796.3  2019
Avatar                           2          Fox  2789.7  2009
Titanic                          3    Paramount  2187.5  1997
Star Wars: The Force Awakens     4  Buena Vista  2068.2  2015
Avengers: Infinity War           5  Buena Vista  2048.4  2018
...                            ...          ...     ...   ...
Ghostbusters II                711     Columbia   215.4  1989
Dirty Dancing                  716      Vestron   214.6  1987
Traffic                        750          USA   207.5  2000
London Has Fallen              756        Focus   205.8  2016
Journey to the West            757        Magn.   205.6  2014

[100 rows x 4 columns]

In [59]:
#Buena Vista 영화들만 모아서 출력
studios.get_group("Buena Vista")

                              Rank       Studio   Gross  Year
Title
Avengers: Endgame                1  Buena Vista  2796.3  2019
Star Wars: The Force Awakens     4  Buena Vista  2068.2  2015
Avengers: Infinity War           5  Buena Vista  2048.4  2018
Marvel's The Avengers            7  Buena Vista  1518.8  2012
Avengers: Age of Ultron          9  Buena Vista  1405.4  2015
...                            ...          ...     ...   ...
Tomorrowland                   745  Buena Vista   209.2  2015
The Jungle Book                755  Buena Vista   205.8  1967
King Arthur                    765  Buena Vista   203.6  2004
Need for Speed                 769  Buena Vista   203.3  2014
Ponyo                          771  Buena Vista   202.4  2009

[125 rows x 4 columns]

In [56]:
#제작사 당 영화 수를 카운트한다.
studios["Gross"].count().head()

Studio
Artisan                     1
Buena Vista               125
CL                          1
China Film Corporation      1
Columbia                    5
Name: Gross, dtype: int64

In [44]:
#내림차순으로 정렬
studios["Gross"].count().sort_values(ascending = False).head()

Studio
Warner Brothers    132
Buena Vista        125
Fox                117
Universal          109
Sony                86
Name: Gross, dtype: int64

In [46]:
#제작사별 수익 합계를 계산
studios["Gross"].sum().head()

Studio
Artisan                     248.6
Buena Vista               73585.0
CL                          228.1
China Film Corporation      699.8
Columbia                   1276.6
Name: Gross, dtype: float64

In [45]:
#내림차순으로 정렬
studios["Gross"].sum().sort_values(ascending = False).head()

Studio
Buena Vista        73585.0
Warner Brothers    58643.8
Fox                50420.8
Universal          44302.3
Sony               32822.5
Name: Gross, dtype: float64

## 1.4 Summary