In [1]:
import pandas as pd

In [2]:
citi_bike=pd.read_csv("citibike.csv")
citi_bike.head()

                 start_time                 stop_time
0  2020-06-01 00:00:03.3720  2020-06-01 00:17:46.2080
1  2020-06-01 00:00:03.5530  2020-06-01 01:03:33.9360
2  2020-06-01 00:00:09.6140  2020-06-01 00:17:06.8330
3  2020-06-01 00:00:12.1780  2020-06-01 00:03:58.8640
4  2020-06-01 00:00:21.2550  2020-06-01 00:24:18.9650

In [3]:
citi_bike.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1882273 entries, 0 to 1882272
Data columns (total 2 columns):
 #   Column      Dtype
---  ------      -----
 0   start_time  object
 1   stop_time   object
dtypes: object(2)
memory usage: 28.7+ MB

In [4]:
#start_time과 stop_time열을 문자열 대신 날짜/시간 값을 저장하도록 변환하세요.
for a in ["start_time","stop_time"]:
    citi_bike[a]=pd.to_datetime(citi_bike[a])

In [5]:
citi_bike.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1882273 entries, 0 to 1882272
Data columns (total 2 columns):
 #   Column      Dtype
---  ------      -----
 0   start_time  datetime64[ns]
 1   stop_time   datetime64[ns]
dtypes: datetime64[ns](2)
memory usage: 28.7 MB

In [9]:
#각 요일에 승차한 건 수를 계산하세요. 사람들이 자전거를 가장 많이 타는 요일은 언제인가요? start_time열을 기준으로 계산하세요.
bike_day=citi_bike["start_time"].dt.day_name()

In [13]:
bike_day.value_counts().sort_values().head(1)

start_time
Thursday    215176
Name: count, dtype: int64

해당 월의 각 주당 승차 건을 구하세요. 이것을 구하려면 start_time열의 각 날짜를 이전 또는 현재 월요일로 변환해야 한다.

한 주가 월요일에서 시작하여 일요일에 끝난다고 가정하세요. 즉, 6월의 첫째주는 6월 1일 월요일부터 6월 7일 일요일까지입니다.

In [20]:
citi_bike["start_time"].dt.dayofweek.head()

0    0
1    0
2    0
3    0
4    0
Name: start_time, dtype: int32

In [21]:
#각 요일이 월요일과 얼만큼 떨어져 있는지 하루에 1씩 더하여 나타낸다.
days_away_from_monday=citi_bike["start_time"].dt.dayofweek

In [22]:
citi_bike["start_time"]-pd.to_timedelta(
    days_away_from_monday,unit="day")

0         2020-06-01 00:00:03.372
1         2020-06-01 00:00:03.553
2         2020-06-01 00:00:09.614
3         2020-06-01 00:00:12.178
4         2020-06-01 00:00:21.255
                    ...
1882268   2020-06-29 23:59:41.116
1882269   2020-06-29 23:59:46.426
1882270   2020-06-29 23:59:47.477
1882271   2020-06-29 23:59:53.395
1882272   2020-06-29 23:59:53.901
Name: start_time, Length: 1882273, dtype: datetime64[ns]

In [24]:
dates_rounded_to_monday=citi_bike["start_time"]-pd.to_timedelta(
    days_away_from_monday,unit="day")

In [25]:
dates_rounded_to_monday.dt.date.head()

0    2020-06-01
1    2020-06-01
2    2020-06-01
3    2020-06-01
4    2020-06-01
Name: start_time, dtype: object

In [27]:
#6월 한 달동안 사람들이 자전거를 가장 많이 탄 주는 15일 월부터 21일 일까지이다.
dates_rounded_to_monday.dt.date.value_counts()

start_time
2020-06-15    481211
2020-06-08    471384
2020-06-22    465412
2020-06-01    337590
2020-06-29    126676
Name: count, dtype: int64

다음문제

In [16]:
#각 승차 시간을 계산하고 결과를 새로운 duration열에 저장하세요.
citi_bike["duration"]=(citi_bike["stop_time"]-citi_bike["start_time"])
citi_bike

                     start_time               stop_time               duration
0       2020-06-01 00:00:03.372 2020-06-01 00:17:46.208 0 days 00:17:42.836000
1       2020-06-01 00:00:03.553 2020-06-01 01:03:33.936 0 days 01:03:30.383000
2       2020-06-01 00:00:09.614 2020-06-01 00:17:06.833 0 days 00:16:57.219000
3       2020-06-01 00:00:12.178 2020-06-01 00:03:58.864 0 days 00:03:46.686000
4       2020-06-01 00:00:21.255 2020-06-01 00:24:18.965 0 days 00:23:57.710000
...                         ...                     ...                    ...
1882268 2020-06-30 23:59:41.116 2020-07-01 00:11:06.779 0 days 00:11:25.663000
1882269 2020-06-30 23:59:46.426 2020-07-01 00:07:13.086 0 days 00:07:26.660000
1882270 2020-06-30 23:59:47.477 2020-07-01 00:07:06.559 0 days 00:07:19.082000
1882271 2020-06-30 23:59:53.395 2020-07-01 00:14:43.427 0 days 00:14:50.032000
1882272 2020-06-30 23:59:53.901 2020-07-01 00:07:07.095 0 days 00:07:13.194000

[1882273 rows x 3 columns]

In [17]:
#자전거를 타는 평균 시간을 구하세요.
citi_bike["duration"].mean()

Timedelta('0 days 00:27:19.590506853')

In [19]:
#데이터셋에서 가장 긴 승차 시간을 5건 추출하세요.
citi_bike["duration"].sort_values(ascending=False).head(5)

50593    32 days 15:01:54.940000
98339    31 days 01:47:20.632000
52306    30 days 19:32:20.696000
15171    30 days 04:26:48.424000
149761   28 days 09:24:50.696000
Name: duration, dtype: timedelta64[ns]