## 11.1 Introducing the Timestamp object

### 11.1.1 How Python works with datetimes

dataset의 시간 정보는 보통 data의 경향을 나타나는 이유를 뒷받침한다.

In [71]:
#날짜/시간을 처리하기 위해 datatime module을 가져온다.
import datetime as dt
import pandas as pd

In [2]:
#date module은 하나의 날짜를 모델링한다. 이때 생성된 object는 시간은 저장하지 않는다.
#그저 년, 월, 일을 저장할 분이다.
# The two lines below are equivalent
birthday = dt.date(1991, 4, 12)
birthday = dt.date(year = 1991, month = 4, day = 12)
birthday

datetime.date(1991, 4, 12)

In [3]:
birthday.year

1991

In [4]:
birthday.month

4

In [5]:
birthday.day

12

**NOTE**: I've commented out the code below so that the Notebook can run without raising an error.

In [6]:
#data object는 불변 object로 생성한 후에는 내부 상태를 변경할 수 없다.
birthday.month = 10

AttributeError: attribute 'month' of 'datetime.date' objects is not writable

In [ ]:
#time class는 특정 시간을 모델링한다. 년, 월, 일은 저장하지 않는다.
#그저 시, 분, 초를 저장한다.
# The two lines below are equivalent
alarm_clock = dt.time(6, 43, 25)
alarm_clock = dt.time(hour = 6, minute = 43, second = 25)
alarm_clock

In [ ]:
alarm_clock.hour

In [7]:
#마찬가지로 내부 상태를 변경할 수 없다.
alarm_clock.hour=8

NameError: name 'alarm_clock' is not defined

In [8]:
dt.time()

datetime.time(0, 0)

In [9]:
dt.time(hour = 9, second = 42)

datetime.time(9, 0, 42)

In [10]:
dt.time(hour = 19, minute = 43, second = 22)

datetime.time(19, 43, 22)

In [11]:
alarm_clock.hour

NameError: name 'alarm_clock' is not defined

In [12]:
alarm_clock.minute

NameError: name 'alarm_clock' is not defined

In [13]:
alarm_clock.second

NameError: name 'alarm_clock' is not defined

In [14]:
#datatime class는 날짜와 시간을 모두 저장한다.
# The two lines below are equivalent
moon_landing = dt.datetime(1969, 7, 20, 22, 56, 20)
moon_landing = dt.datetime(
    year = 1969,
    month = 7,
    day = 20,
    hour = 22,
    minute = 56,
    second = 20
)
moon_landing

datetime.datetime(1969, 7, 20, 22, 56, 20)

In [15]:
dt.datetime(2020, 1, 1)

datetime.datetime(2020, 1, 1, 0, 0)

In [16]:
#year, month, day매개변수에는 필수로 값을 전달해야 한다.
dt.datetime()

TypeError: function missing required argument 'year' (pos 1)

In [17]:
#timedelta class는 시간차를 모델링한다.
#매개변수로 전달된 시간의 길이를 합하여 총 시간을 계산한다.
#다음은 8주와 6일을 더하고 3시간 58분 12초를 더하여 총 62일 14,292초를 계산한다.
dt.timedelta(
    weeks = 8,
    days = 6,
    hours = 3, 
    minutes = 58,
    seconds = 12
)

datetime.timedelta(days=62, seconds=14292)

### 11.1.2 How `pandas` works with datetimes

pandas는 datetime class를 대체하기 위해 Timestamp class를 도입했다.

Timestamp object는 날짜와 더불어 내부적으로 시간도 저장한다.

In [18]:
#Timestamp object와 datatime object생성법은 똑같다.
# The two lines below are equivalent
pd.Timestamp(1991, 4, 12)
pd.Timestamp(year = 1991, month = 4, day = 12)

Timestamp('1991-04-12 00:00:00')

In [19]:
#Timestamp object와 date의 date object가 같은지 확인할 수도 잇다.
#날짜 혹은 시간이 다르면 두 object는 동일하지 않다.
(pd.Timestamp(year = 1991, month = 4, day = 12) 
 == dt.date(year = 1991, month = 4, day = 12))

False

In [20]:
(pd.Timestamp(year = 1991, month = 4, day = 12, minute = 2)
 == dt.datetime(year = 1991, month = 4, day = 12, minute = 2))

True

In [21]:
(pd.Timestamp(year = 1991, month = 4, day = 12, minute = 2) 
 == dt.datetime(year = 1991, month = 4, day = 12, minute = 1))

False

In [22]:
#YYYY-MM-DD형식으로 날짜를 나타내도 된다.
pd.Timestamp("2015-03-31")

Timestamp('2015-03-31 00:00:00')

In [23]:
#-대신 /를 사용해도 된다.
pd.Timestamp("2015/03/31")

Timestamp('2015-03-31 00:00:00')

In [24]:
#MM/DD/YYYY형식의 문자열을 전달해도 된다.
pd.Timestamp("03/31/2015")

Timestamp('2015-03-31 00:00:00')

In [25]:
pd.Timestamp("2021-03-08 08:35:15")

Timestamp('2021-03-08 08:35:15')

In [26]:
pd.Timestamp("2021-03-08 6:13:29 PM")

Timestamp('2021-03-08 18:13:29')

In [27]:
#Timestamp생성자는 python의 기본 date, time 및 datetime object도 허용한다.
pd.Timestamp(dt.datetime(2000, 2, 3, 21, 35, 22))

Timestamp('2000-02-03 21:35:22')

In [28]:
my_time = pd.Timestamp(dt.datetime(2000, 2, 3, 21, 35, 22))
print(my_time.year) 
print(my_time.month)
print(my_time.day)
print(my_time.hour) 
print(my_time.minute)
print(my_time.second)

2000
2
3
21
35
22

## 11.2 Storing Multiple Timestamps in a DatetimeIndex

index는 pandas 자료구조에 붙여지는 식별자 label collection을 의미한다. 

지금까지는 오름차순 혹은 내림차순으로 정렬된 숫자 값의 시퀀스인 RangeIndex를 사용했다.

In [29]:
#index속성으로 Series의 index에 접근
pd.Series([1, 2, 3]).index

RangeIndex(start=0, stop=3, step=1)

pandas는 Index object를 사용해서 문자열 label collection을 저장한다.

In [30]:
#index속성으로 DataFrame의 index에 접근
pd.Series([1, 2, 3], index = ["A", "B", "C"]).index

Index(['A', 'B', 'C'], dtype='object')

DatatimeIndex는 Timestamp object를 저장하는 index이다.

In [31]:
#Series의 index를 DatetimeIndex로 설정하였다.
timestamps = [
    pd.Timestamp("2020-01-01"),
    pd.Timestamp("2020-02-01"),
    pd.Timestamp("2020-03-01"),
]

pd.Series([1, 2, 3], index = timestamps).index

DatetimeIndex(['2020-01-01', '2020-02-01', '2020-03-01'], dtype='datetime64[ns]', freq=None)

In [32]:
pd.Series([1, 2, 3], index = timestamps)

2020-01-01    1
2020-02-01    2
2020-03-01    3
dtype: int64

In [33]:
datetimes = [
    dt.datetime(2020, 1, 1),
    dt.datetime(2020, 2, 1),
    dt.datetime(2020, 3, 1),
]

pd.Series([1, 2, 3], index = datetimes).index

DatetimeIndex(['2020-01-01', '2020-02-01', '2020-03-01'], dtype='datetime64[ns]', freq=None)

In [34]:
#다음과 같이 DatetimeIndex자체를 생성할 수도 있다.
#이때 매개변수는 모든 반복 가능한 날짜 collection을 인수로 전달받는다.
#날짜를 문자열, 날자/시간, Timestamp 또는 혼합 데이터 유형으로 전달할 수 있다.
#pandas는 모든 값을 동등하게 Timestmp로 변환하고 index에 저장한다.
string_dates = ["2018/01/02", "2016/04/12", "2009/09/07"]
pd.DatetimeIndex(string_dates)

DatetimeIndex(['2018-01-02', '2016-04-12', '2009-09-07'], dtype='datetime64[ns]', freq=None)

In [35]:
mixed_dates = [
    dt.date(2018, 1, 2),
    "2016/04/12",
    pd.Timestamp(2009, 9, 7)
]

dt_index = pd.DatetimeIndex(mixed_dates)
dt_index

DatetimeIndex(['2018-01-02', '2016-04-12', '2009-09-07'], dtype='datetime64[ns]', freq=None)

In [36]:
#이제 Series의 index에 Timestamp object를 저장하는 index인 DatatimeIndex를 저장한다.
s = pd.Series(data = [100, 200, 300], index = dt_index)
s

2018-01-02    100
2016-04-12    200
2009-09-07    300
dtype: int64

pandas에서는 날짜/시간 값을 문자열이 아닌 Timestamp로 저장해야만 날짜 및 시간과 관련된 연산을 적용할 수 있다.

In [37]:
s.sort_index()

2009-09-07    300
2016-04-12    200
2018-01-02    100
dtype: int64

In [38]:
morning = pd.Timestamp("2020-01-01 11:23:22 AM")
evening = pd.Timestamp("2020-01-01 11:23:22 PM")

morning < evening

True

## 11.3	Converting Column or Index Values to Datetimes

read_csv()는 기본적으로 숫자가 아닌 열의 모든 값을 문자열로 갖고 온다.

In [39]:
disney = pd.read_csv("disney.csv")
disney.head()

         Date      High       Low      Open     Close
0  1962-01-02  0.096026  0.092908  0.092908  0.092908
1  1962-01-03  0.094467  0.092908  0.092908  0.094155
2  1962-01-04  0.094467  0.093532  0.094155  0.094155
3  1962-01-05  0.094779  0.093844  0.094155  0.094467
4  1962-01-08  0.095714  0.092285  0.094467  0.094155

In [40]:
disney.dtypes

Date      object
High     float64
Low      float64
Open     float64
Close    float64
dtype: object

In [41]:
disney = pd.read_csv("disney.csv", parse_dates = ["Date"])

In [42]:
string_dates = ["2015-01-01", "2016-02-02", "2017-03-03"]
#to_datetime()은 반복 가능한 object(list, tuple, Series, index등)을 받아서 해당 값을 datetime으로 변환하고 DatetimeIndex에 값을 담아 변환한다.
dt_index = pd.to_datetime(string_dates)
dt_index

DatetimeIndex(['2015-01-01', '2016-02-02', '2017-03-03'], dtype='datetime64[ns]', freq=None)

In [43]:
pd.to_datetime(disney["Date"]).head()

0   1962-01-02
1   1962-01-03
2   1962-01-04
3   1962-01-05
4   1962-01-08
Name: Date, dtype: datetime64[ns]

In [44]:
type(pd.to_datetime(disney["Date"]))

pandas.core.series.Series

In [45]:
disney["Date"] = pd.to_datetime(disney["Date"])

In [46]:
disney.dtypes

Date     datetime64[ns]
High            float64
Low             float64
Open            float64
Close           float64
dtype: object

## 11.4 Using the DatetimeProperties Object

In [47]:
#날짜/시간 Series는 dt속성을 통해 DatetimeProperties object에 접근할 수 있다.
disney["Date"].dt

DatetimeProperties object의 속성에 접근하고 method를 호출하여 열의 datetime에서 정보를 추출할 수 있다.

In [48]:
disney["Date"].head(3)

0   1962-01-02
1   1962-01-03
2   1962-01-04
Name: Date, dtype: datetime64[ns]

In [49]:
#DatetimeProperties object의 day속성으로 각 날짜에서 일(day)을 가져온다.
disney["Date"].dt.day.head(3)

0    2
1    3
2    4
Name: Date, dtype: int32

In [50]:
#DatetimeProperties object의 month속성으로 각 날짜의 월을 가져온다.
disney["Date"].dt.month.head(3)

0    1
1    1
2    1
Name: Date, dtype: int32

In [51]:
disney["Date"].dt.year.head(3)

0    1962
1    1962
2    1962
Name: Date, dtype: int32

In [52]:
#DatetimeProperties object의 dayofweek속성은 날짜의 요일에 대한 숫자를 담은 Series를 반환한다.
#0부터 6까지 순서대로 월요일에서 일요일을 나타낸다.
disney["Date"].dt.dayofweek.head()

0    1
1    2
2    3
3    4
4    0
Name: Date, dtype: int32

In [53]:
#숫자 대신 요일의 이름을 출력하고 싶다면 day_name()를 사용하면 된다.
disney["Date"].dt.day_name().head()

0      Tuesday
1    Wednesday
2     Thursday
3       Friday
4       Monday
Name: Date, dtype: object

In [54]:
#DataFrame에 위 Series를 추가한다.
disney["Day of Week"] = disney["Date"].dt.day_name()

In [55]:
#DataFrame을 "Day of Week"로 그룹화한다.
group = disney.groupby("Day of Week")

In [56]:
#각 요일에 대한 주가의 평균을 계산한다.
group.mean(numeric_only=True)

                  High        Low       Open      Close
Day of Week
Friday       23.767304  23.318898  23.552872  23.554498
Monday       23.377271  22.930606  23.161392  23.162543
Thursday     23.770234  23.288687  23.534561  23.540359
Tuesday      23.791234  23.335267  23.571755  23.562907
Wednesday    23.842743  23.355419  23.605618  23.609873

In [57]:
#month_name()는 날짜의 월 이름이 포함된 Series를 반환한다.
disney["Date"].dt.month_name().head()

0    January
1    January
2    January
3    January
4    January
Name: Date, dtype: object

In [58]:
#is_quarter_start속성은 각 행의 날짜가 분기의 시작 날짜와 같으면 True를 반환한다.
disney["Date"].dt.is_quarter_start.tail()

14722    False
14723    False
14724    False
14725     True
14726    False
Name: Date, dtype: bool

In [59]:
#is_quarter_start속성을 통해 분기 시작 일에 해당하는 행만을 추출할 수 있다.
disney[disney["Date"].dt.is_quarter_start].head()

          Date      High       Low      Open     Close Day of Week
189 1962-10-01  0.064849  0.062355  0.063913  0.062355      Monday
314 1963-04-01  0.087989  0.086704  0.087025  0.086704      Monday
377 1963-07-01  0.096338  0.095053  0.096338  0.095696      Monday
441 1963-10-01  0.110467  0.107898  0.107898  0.110467     Tuesday
565 1964-04-01  0.116248  0.112394  0.112394  0.116248   Wednesday

In [60]:
#is_quarter_end속성은 분기 마지막 날에 해당하는 날짜를 가져올 수 있다.
disney[disney["Date"].dt.is_quarter_end].head()

          Date      High       Low      Open     Close Day of Week
251 1962-12-31  0.074501  0.071290  0.074501  0.072253      Monday
440 1963-09-30  0.109825  0.105972  0.108541  0.107577      Monday
502 1963-12-31  0.101476  0.096980  0.097622  0.101476     Tuesday
564 1964-03-31  0.115605  0.112394  0.114963  0.112394     Tuesday
628 1964-06-30  0.101476  0.100191  0.101476  0.100834     Tuesday

In [61]:
#날짜가 월 시작인 날짜만 추출
disney[disney["Date"].dt.is_month_start].head()

          Date      High       Low      Open     Close Day of Week
22  1962-02-01  0.096338  0.093532  0.093532  0.094779    Thursday
41  1962-03-01  0.095714  0.093532  0.093532  0.095714    Thursday
83  1962-05-01  0.087296  0.085426  0.085738  0.086673     Tuesday
105 1962-06-01  0.079814  0.077943  0.079814  0.079814      Friday
147 1962-08-01  0.068590  0.068278  0.068590  0.068590   Wednesday

In [62]:
#날짜가 월 끝인 날짜만 추출
disney[disney["Date"].dt.is_month_end].head()

          Date      High       Low      Open     Close Day of Week
21  1962-01-31  0.093844  0.092908  0.093532  0.093532   Wednesday
40  1962-02-28  0.094779  0.093220  0.094155  0.093220   Wednesday
82  1962-04-30  0.087608  0.085738  0.087608  0.085738      Monday
104 1962-05-31  0.082308  0.079814  0.079814  0.079814    Thursday
146 1962-07-31  0.069214  0.068278  0.068278  0.068590     Tuesday

In [63]:
#is_year_start는 날짜가 연도의 첫날이면 True를 반환한다.
disney[disney["Date"].dt.is_year_start].head()

Empty DataFrame
Columns: [Date, High, Low, Open, Close, Day of Week]
Index: []

In [64]:
#is_year_start는 날짜가 연도의 마지막 날이면 True를 반환한다.
disney[disney["Date"].dt.is_year_end].head()

           Date      High       Low      Open     Close Day of Week
251  1962-12-31  0.074501  0.071290  0.074501  0.072253      Monday
502  1963-12-31  0.101476  0.096980  0.097622  0.101476     Tuesday
755  1964-12-31  0.117853  0.116890  0.116890  0.116890    Thursday
1007 1965-12-31  0.154141  0.150929  0.153498  0.152214      Friday
1736 1968-12-31  0.439301  0.431594  0.434163  0.436732     Tuesday

## 11.5 Adding and Subtracting Durations of Time

In [67]:
#DateOffset object를 사용하여 일관된 시간을 더하거나 뺄 수 있다.
pd.DateOffset(years = 3, months = 4, days = 5)

In [68]:
disney["Date"].head()

0   1962-01-02
1   1962-01-03
2   1962-01-04
3   1962-01-05
4   1962-01-08
Name: Date, dtype: datetime64[ns]

In [69]:
#+와 DateOffset object를 사용해서 날짜/시간 Series의 각 날짜에 일관된 시간을 추가할 수 있다.
(disney["Date"] + pd.DateOffset(days = 5)).head()

0   1962-01-07
1   1962-01-08
2   1962-01-09
3   1962-01-10
4   1962-01-13
Name: Date, dtype: datetime64[ns]

In [70]:
#-는 날짜/시간 Series의 각 날짜에서 시간을 뺀다.
(disney["Date"] - pd.DateOffset(days = 3)).head()

0   1961-12-30
1   1961-12-31
2   1962-01-01
3   1962-01-02
4   1962-01-05
Name: Date, dtype: datetime64[ns]

In [72]:
#Date의 각 날짜/시간에 일관된 시간을 추가한다.
(disney["Date"] + pd.DateOffset(days = 10, hours = 6)).head()

0   1962-01-12 06:00:00
1   1962-01-13 06:00:00
2   1962-01-14 06:00:00
3   1962-01-15 06:00:00
4   1962-01-18 06:00:00
Name: Date, dtype: datetime64[ns]

In [73]:
(
    disney["Date"]
    - pd.DateOffset(
        years = 1, months = 3, days = 10, hours = 6, minutes = 3
    )
).head()

0   1960-09-21 17:57:00
1   1960-09-22 17:57:00
2   1960-09-23 17:57:00
3   1960-09-24 17:57:00
4   1960-09-27 17:57:00
Name: Date, dtype: datetime64[ns]

## 11.6 Date Offsets

In [74]:
disney["Date"].tail()

14722   2020-06-26
14723   2020-06-29
14724   2020-06-30
14725   2020-07-01
14726   2020-07-02
Name: Date, dtype: datetime64[ns]

In [77]:
#offset object의 MonthEnd object는 각 날짜를 다음 달 말일로 올린다.
#이미 말일인 2020-6-30은 다음달 말일인 2020-07-31로 올린다.
(disney["Date"] + pd.offsets.MonthEnd()).tail()

14722   2020-06-30
14723   2020-06-30
14724   2020-07-31
14725   2020-07-31
14726   2020-07-31
Name: Date, dtype: datetime64[ns]

In [78]:
#이때 빼기 기호는 각 날짜를 시간상 뒤로 이동시킨다. 즉 이전 달의 말일로 내린다.
(disney["Date"] - pd.offsets.MonthEnd()).tail()

14722   2020-05-31
14723   2020-05-31
14724   2020-05-31
14725   2020-06-30
14726   2020-06-30
Name: Date, dtype: datetime64[ns]

In [79]:
#MonthBegin은 월의 첫 번째 날짜로 올린다.
#+기호와 사용시 각 날짜를 다음달 시작일로 올린다.
(disney["Date"] + pd.offsets.MonthBegin()).tail()

14722   2020-07-01
14723   2020-07-01
14724   2020-07-01
14725   2020-08-01
14726   2020-08-01
Name: Date, dtype: datetime64[ns]

In [80]:
#-기호와 사용시 각 날짜를 월의 시작일로 내린다.
#만약 2020-07-01인 경우 2020-06-01로 내린다.
(disney["Date"] - pd.offsets.MonthBegin()).tail()

14722   2020-06-01
14723   2020-06-01
14724   2020-06-01
14725   2020-06-01
14726   2020-07-01
Name: Date, dtype: datetime64[ns]

In [81]:
may_dates = ["2020-05-28", "2020-05-29", "2020-05-30"]
end_of_may = pd.Series(pd.to_datetime(may_dates))
end_of_may

0   2020-05-28
1   2020-05-29
2   2020-05-30
dtype: datetime64[ns]

In [82]:
end_of_may + pd.offsets.MonthEnd()

0   2020-05-31
1   2020-05-31
2   2020-05-31
dtype: datetime64[ns]

In [83]:
#BMonthEnd()는 업무상 월 마지막 영업일로 올린다.
end_of_may + pd.offsets.BMonthEnd()

0   2020-05-29
1   2020-06-30
2   2020-06-30
dtype: datetime64[ns]

## 11.7 The `timedelta` Object

In [84]:
duration = pd.Timedelta(
    days = 8,
    hours = 7,
    minutes = 6,
    seconds = 5
)

duration

Timedelta('8 days 07:06:05')

In [86]:
#to_timedelta()는 전달된 인수를 Timedelta object로 변환한다.
pd.to_timedelta("3 hours, 5 minutes, 12 seconds")

Timedelta('0 days 03:05:12')

In [87]:
#unit 매개변수는 숫자가 나타내는 시간 단위를 정의한다.
pd.to_timedelta(5, unit = "hour")

Timedelta('0 days 05:00:00')

In [88]:
pd.to_timedelta([5, 10, 15], unit = "day")

TimedeltaIndex(['5 days', '10 days', '15 days'], dtype='timedelta64[ns]', freq=None)

In [89]:
#한 Timestamp에서 다른 Timestamp를 빼면 자동으로 Timedelta가 반환된다.
pd.Timestamp("1999-02-05") - pd.Timestamp("1998-05-24")

Timedelta('257 days 00:00:00')

In [90]:
deliveries = pd.read_csv("deliveries.csv")
deliveries.head()

  order_date delivery_date
0    5/24/98        2/5/99
1    4/22/92        3/6/98
2    2/10/91       8/26/92
3    7/21/92      11/20/97
4     9/2/93       6/10/98

In [93]:
#to_datetime()를 통해 문자열을 datetime object로 변환한다.
deliveries["order_date"] = pd.to_datetime(
    deliveries["order_date"]
)

deliveries["delivery_date"] = pd.to_datetime(
    deliveries["delivery_date"]
)

In [95]:
#반복문을 사용하여 위 과정을 수행하였다.
for column in ["order_date", "delivery_date"]:
    deliveries[column] = pd.to_datetime(deliveries[column])

In [96]:
deliveries.head()

  order_date delivery_date
0 1998-05-24    1999-02-05
1 1992-04-22    1998-03-06
2 1991-02-10    1992-08-26
3 1992-07-21    1997-11-20
4 1993-09-02    1998-06-10

In [99]:
#delivery_date열에서 order_date열을 빼서 각 배송 기간을 계산할 수도 있다.
#그럼 계산 결과가 timedelta Series로 반환된다.
(deliveries["delivery_date"] - deliveries["order_date"]).head()

0    257 days
1   2144 days
2    563 days
3   1948 days
4   1742 days
dtype: timedelta64[ns]

In [103]:
print(type((deliveries["delivery_date"] - deliveries["order_date"])))
print(type((deliveries["delivery_date"] - deliveries["order_date"])[1]))

<class 'pandas.core.series.Series'>
<class 'pandas._libs.tslibs.timedeltas.Timedelta'>

In [104]:
deliveries["duration"] = (
    deliveries["delivery_date"] - deliveries["order_date"]
)
deliveries.head()

  order_date delivery_date  duration
0 1998-05-24    1999-02-05  257 days
1 1992-04-22    1998-03-06 2144 days
2 1991-02-10    1992-08-26  563 days
3 1992-07-21    1997-11-20 1948 days
4 1993-09-02    1998-06-10 1742 days

In [105]:
deliveries.dtypes

order_date        datetime64[ns]
delivery_date     datetime64[ns]
duration         timedelta64[ns]
dtype: object

In [106]:
(deliveries["delivery_date"] - deliveries["duration"]).head()

0   1998-05-24
1   1992-04-22
2   1991-02-10
3   1992-07-21
4   1993-09-02
dtype: datetime64[ns]

In [107]:
(deliveries["delivery_date"] + deliveries["duration"]).head()

0   1999-10-20
1   2004-01-18
2   1994-03-12
3   2003-03-22
4   2003-03-18
dtype: datetime64[ns]

In [108]:
deliveries.sort_values("duration")

    order_date delivery_date  duration
454 1990-05-24    1990-06-01    8 days
294 1994-08-11    1994-08-20    9 days
10  1998-05-10    1998-05-19    9 days
499 1993-06-03    1993-06-13   10 days
143 1997-09-20    1997-10-06   16 days
..         ...           ...       ...
152 1990-09-18    1999-12-19 3379 days
62  1990-04-02    1999-08-16 3423 days
458 1990-02-13    1999-11-15 3562 days
145 1990-03-07    1999-12-25 3580 days
448 1990-01-20    1999-11-12 3583 days

[501 rows x 3 columns]

다음과 같이 Timedelta Series에서도 수학 method를 사용할 수 있다.

In [109]:
deliveries["duration"].max()

Timedelta('3583 days 00:00:00')

In [110]:
deliveries["duration"].min()

Timedelta('8 days 00:00:00')

In [111]:
deliveries["duration"].mean()

Timedelta('1217 days 22:53:53.532934128')

다음과 같이 filtering을 할 수도 있다.

In [112]:
# The two lines below are equivalent
(deliveries["duration"] > pd.Timedelta(days = 365)).head() 
(deliveries["duration"] > "365 days").head()

0    False
1     True
2     True
3     True
4     True
Name: duration, dtype: bool

In [114]:
#배송기간이 365일보다 긴 행을 filtering
deliveries[deliveries["duration"] > "365 days"].head()

  order_date delivery_date  duration
1 1992-04-22    1998-03-06 2144 days
2 1991-02-10    1992-08-26  563 days
3 1992-07-21    1997-11-20 1948 days
4 1993-09-02    1998-06-10 1742 days
6 1990-01-25    1994-10-02 1711 days

In [115]:
#비교하는 시간을 좀 더 세분화할 수도 있다.
long_time = (
    deliveries["duration"] > "2000 days, 8 hours, 4 minutes"
)

deliveries[long_time].head()

   order_date delivery_date  duration
1  1992-04-22    1998-03-06 2144 days
7  1992-02-23    1998-12-30 2502 days
11 1992-10-17    1998-10-06 2180 days
12 1992-05-30    1999-08-15 2633 days
15 1990-01-20    1998-07-24 3107 days

## 11.8 Coding Challenge

### 11.8.1 Problems

In [97]:
citi_bike = pd.read_csv("citibike.csv")
citi_bike.head()

                 start_time                 stop_time
0  2020-06-01 00:00:03.3720  2020-06-01 00:17:46.2080
1  2020-06-01 00:00:03.5530  2020-06-01 01:03:33.9360
2  2020-06-01 00:00:09.6140  2020-06-01 00:17:06.8330
3  2020-06-01 00:00:12.1780  2020-06-01 00:03:58.8640
4  2020-06-01 00:00:21.2550  2020-06-01 00:24:18.9650

In [98]:
citi_bike.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1882273 entries, 0 to 1882272
Data columns (total 2 columns):
 #   Column      Dtype
---  ------      -----
 0   start_time  object
 1   stop_time   object
dtypes: object(2)
memory usage: 28.7+ MB

### 11.8.2. Solutions

In [99]:
for column in ["start_time", "stop_time"]:
    citi_bike[column] = pd.to_datetime(citi_bike[column])

In [100]:
citi_bike.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1882273 entries, 0 to 1882272
Data columns (total 2 columns):
 #   Column      Dtype
---  ------      -----
 0   start_time  datetime64[ns]
 1   stop_time   datetime64[ns]
dtypes: datetime64[ns](2)
memory usage: 28.7 MB

In [101]:
citi_bike["start_time"].dt.day_name().head()

0    Monday
1    Monday
2    Monday
3    Monday
4    Monday
Name: start_time, dtype: object

In [102]:
citi_bike["start_time"].dt.day_name().value_counts()

Tuesday      305833
Sunday       301482
Monday       292690
Saturday     285966
Friday       258479
Wednesday    222647
Thursday     215176
Name: start_time, dtype: int64

In [103]:
citi_bike["start_time"].dt.dayofweek.head()

0    0
1    0
2    0
3    0
4    0
Name: start_time, dtype: int64

In [104]:
days_away_from_monday = citi_bike["start_time"].dt.dayofweek

In [105]:
citi_bike["start_time"] - pd.to_timedelta(
    days_away_from_monday, unit = "day"
)

0         2020-06-01 00:00:03.372
1         2020-06-01 00:00:03.553
2         2020-06-01 00:00:09.614
3         2020-06-01 00:00:12.178
4         2020-06-01 00:00:21.255
                    ...
1882268   2020-06-29 23:59:41.116
1882269   2020-06-29 23:59:46.426
1882270   2020-06-29 23:59:47.477
1882271   2020-06-29 23:59:53.395
1882272   2020-06-29 23:59:53.901
Name: start_time, Length: 1882273, dtype: datetime64[ns]

In [106]:
dates_rounded_to_monday = citi_bike[
    "start_time"
] - pd.to_timedelta(days_away_from_monday, unit = "day")

In [107]:
dates_rounded_to_monday.value_counts().head()

2020-06-22 20:13:36.208    3
2020-06-08 17:17:26.335    3
2020-06-08 16:50:44.596    3
2020-06-15 19:24:26.737    3
2020-06-08 19:49:21.686    3
Name: start_time, dtype: int64

In [108]:
dates_rounded_to_monday.dt.date.head()

0    2020-06-01
1    2020-06-01
2    2020-06-01
3    2020-06-01
4    2020-06-01
Name: start_time, dtype: object

In [109]:
dates_rounded_to_monday.dt.date.value_counts()

2020-06-15    481211
2020-06-08    471384
2020-06-22    465412
2020-06-01    337590
2020-06-29    126676
Name: start_time, dtype: int64

In [110]:
citi_bike["duration"] = (
    citi_bike["stop_time"] - citi_bike["start_time"]
)

citi_bike.head()

               start_time               stop_time               duration
0 2020-06-01 00:00:03.372 2020-06-01 00:17:46.208 0 days 00:17:42.836000
1 2020-06-01 00:00:03.553 2020-06-01 01:03:33.936 0 days 01:03:30.383000
2 2020-06-01 00:00:09.614 2020-06-01 00:17:06.833 0 days 00:16:57.219000
3 2020-06-01 00:00:12.178 2020-06-01 00:03:58.864 0 days 00:03:46.686000
4 2020-06-01 00:00:21.255 2020-06-01 00:24:18.965 0 days 00:23:57.710000

In [111]:
citi_bike["duration"].mean()

Timedelta('0 days 00:27:19.590506853')

In [112]:
citi_bike["duration"].sort_values(ascending = False).head()

50593    32 days 15:01:54.940000
98339    31 days 01:47:20.632000
52306    30 days 19:32:20.696000
15171    30 days 04:26:48.424000
149761   28 days 09:24:50.696000
Name: duration, dtype: timedelta64[ns]

In [113]:
citi_bike.nlargest(n = 5, columns = "duration")

                    start_time               stop_time                duration
50593  2020-06-01 21:30:17.759 2020-07-04 12:32:12.699 32 days 15:01:54.940000
98339  2020-06-02 19:41:39.659 2020-07-03 21:29:00.291 31 days 01:47:20.632000
52306  2020-06-01 22:17:10.908 2020-07-02 17:49:31.604 30 days 19:32:20.696000
15171  2020-06-01 13:01:41.942 2020-07-01 17:28:30.366 30 days 04:26:48.424000
149761 2020-06-04 14:36:53.482 2020-07-03 00:01:44.178 28 days 09:24:50.696000

## 11.9 Summary