## 3.1 Importing a Data Set with the read_csv Function

In [1]:
import pandas as pd

pandas library에 있는 CSV파일을 가져오는 함수인 read_csv()의 출력값은 항상 2차원 DataFrame이다.

In [2]:
# The two lines below are equivalent
pd.read_csv(filepath_or_buffer = "pokemon.csv")
pd.read_csv("pokemon.csv")

         Pokemon            Type
0      Bulbasaur  Grass / Poison
1        Ivysaur  Grass / Poison
2       Venusaur  Grass / Poison
3     Charmander            Fire
4     Charmeleon            Fire
..           ...             ...
804    Stakataka    Rock / Steel
805  Blacephalon    Fire / Ghost
806      Zeraora        Electric
807       Meltan           Steel
808     Melmetal           Steel

[809 rows x 2 columns]

In [11]:
#index_col라는 매개변수를 사용하여 DataFrame의 여러 column중 하나를 index label로 설정할 수 있다.
poket=pd.read_csv("pokemon.csv", index_col = "Pokemon")
poket

                       Type
Pokemon
Bulbasaur    Grass / Poison
Ivysaur      Grass / Poison
Venusaur     Grass / Poison
Charmander             Fire
Charmeleon             Fire
...                     ...
Stakataka      Rock / Steel
Blacephalon    Fire / Ghost
Zeraora            Electric
Meltan                Steel
Melmetal              Steel

[809 rows x 1 columns]

In [13]:
#column의 개수가 1개 밖에 없어도 Series타입이 아닌 DataFrame타입이다.
type(poket)

pandas.core.frame.DataFrame

In [26]:
#1개의 column을 갖는 DataFrame을 Series로 변환하고 싶으면, DataFrame 클래스에 있는 squeeze() method을 사용하면 된다. 
pokemon=pd.read_csv("pokemon.csv", index_col = "Pokemon")
print(type(pokemon.squeeze()))
pokemon=pokemon.squeeze()
pokemon
#위 Series의 index label은 pokemon의 이름이고 value는 pokemon의 유형이다.

<class 'pandas.core.series.Series'>

Pokemon
Bulbasaur      Grass / Poison
Ivysaur        Grass / Poison
Venusaur       Grass / Poison
Charmander               Fire
Charmeleon               Fire
                    ...
Stakataka        Rock / Steel
Blacephalon      Fire / Ghost
Zeraora              Electric
Meltan                  Steel
Melmetal                Steel
Name: Type, Length: 809, dtype: object

In [21]:
pd.read_csv("google_stocks.csv").head()

         Date  Close
0  2004-08-19  49.98
1  2004-08-20  53.95
2  2004-08-23  54.50
3  2004-08-24  52.24
4  2004-08-25  52.80

In [23]:
#parse_dates매개변수는 pandas가 날짜/시간으로 변환해야 하는 텍스트 값의 열을 나타내는 문자열 리스트를 인수로 받는다.
#이때는 "Date"라는 column의 이름이 담긴 문자열 리스트가 인수로 전달되었다.
pd.read_csv("google_stocks.csv", parse_dates = ["Date"]).head()

        Date  Close
0 2004-08-19  49.98
1 2004-08-20  53.95
2 2004-08-23  54.50
3 2004-08-24  52.24
4 2004-08-25  52.80

In [29]:
#Date라는 column을 문자열이 아닌 다른 데이터 유형으로 저장하고, 이를 index label로 사용하는 Series을 구성한다.
google=pd.read_csv(
    "google_stocks.csv",
    parse_dates = ["Date"],
    index_col = "Date"
)
google=google.squeeze()
google

Date
2004-08-19      49.98
2004-08-20      53.95
2004-08-23      54.50
2004-08-24      52.24
2004-08-25      52.80
               ...
2019-10-21    1246.15
2019-10-22    1242.80
2019-10-23    1259.13
2019-10-24    1260.99
2019-10-25    1265.13
Name: Close, Length: 3824, dtype: float64

In [30]:
pd.read_csv("revolutionary_war.csv").tail()

                         Battle  Start Date     State
227         Siege of Fort Henry   9/11/1782  Virginia
228  Grand Assault on Gibraltar   9/13/1782       NaN
229   Action of 18 October 1782  10/18/1782       NaN
230   Action of 6 December 1782   12/6/1782       NaN
231   Action of 22 January 1783   1/22/1783  Virginia

In [32]:
pd.read_csv(
    "revolutionary_war.csv",
    index_col = "Start Date",
    parse_dates = ["Start Date"],
).tail()

                                Battle     State
Start Date
1782-09-11         Siege of Fort Henry  Virginia
1782-09-13  Grand Assault on Gibraltar       NaN
1782-10-18   Action of 18 October 1782       NaN
1782-12-06   Action of 6 December 1782       NaN
1783-01-22   Action of 22 January 1783  Virginia

In [75]:
#Start Date column의 문자열을 날짜/시간 값으로 변환하고, 이를 index label로 활용한다.
#이때의 DataFrame의 column의 개수는 3개인데, Series로 변환하고 싶다면 2개의 column만을 가져와야 한다.
#하나는 index label용이고, 다른 하나는 value용이다.
#usecols라는 매개변수로 CSV파일에서 가져와야 하는 column의 목록을 (문자열 리스트 형태로) 인자로 받는다.
battles = pd.read_csv(
    "revolutionary_war.csv",
    index_col = "Start Date",
    parse_dates = ["Start Date"],
    usecols = ["State", "Start Date"]  
).squeeze()
battles

Start Date
1774-09-01    Massachusetts
1774-12-14    New Hampshire
1775-04-19    Massachusetts
1775-04-19    Massachusetts
1775-04-20         Virginia
                  ...
1782-09-11         Virginia
1782-09-13              NaN
1782-10-18              NaN
1782-12-06              NaN
1783-01-22         Virginia
Name: State, Length: 232, dtype: object

## 3.2 Sorting a Series

### 3.2.1 Sorting by Values with the sort_values Method

In [38]:
#value을 기준으로 오름차순으로 정렬된 새 Series을 반환한다.
google.sort_values()

Date
2004-09-03      49.82
2004-09-01      49.94
2004-08-19      49.98
2004-09-02      50.57
2004-09-07      50.60
               ...
2019-04-23    1264.55
2019-10-25    1265.13
2018-07-26    1268.33
2019-04-26    1272.18
2019-04-29    1287.58
Name: Close, Length: 3824, dtype: float64

In [39]:
pokemon.sort_values()

Pokemon
Illumise                Bug
Silcoon                 Bug
Pinsir                  Bug
Burmy                   Bug
Wurmple                 Bug
                  ...
Tirtouga       Water / Rock
Relicanth      Water / Rock
Corsola        Water / Rock
Carracosta     Water / Rock
Empoleon      Water / Steel
Name: Type, Length: 809, dtype: object

In [40]:
#pandas는 대문자를 소문자보다 먼저 정렬한다.
pd.Series(data = ["Adam", "adam", "Ben"]).sort_values()

0    Adam
2     Ben
1    adam
dtype: object

In [43]:
#내림차순으로 정렬하고 싶다면 ascending에 False을 전달하면 도니다.
google.sort_values(ascending = False)

Date
2019-04-29    1287.58
2019-04-26    1272.18
2018-07-26    1268.33
2019-10-25    1265.13
2019-04-23    1264.55
               ...
2004-09-07      50.60
2004-09-02      50.57
2004-08-19      49.98
2004-09-01      49.94
2004-09-03      49.82
Name: Close, Length: 3824, dtype: float64

In [44]:
pokemon.sort_values(ascending = False)

Pokemon
Empoleon      Water / Steel
Corsola        Water / Rock
Relicanth      Water / Rock
Carracosta     Water / Rock
Tirtouga       Water / Rock
                  ...
Kricketune              Bug
Cascoon                 Bug
Scatterbug              Bug
Kricketot               Bug
Grubbin                 Bug
Name: Type, Length: 809, dtype: object

In [46]:
# The two lines below are equivalent
battles.sort_values()
#na_position매개변수는 반환된 Series에서 NaN값을 어디에 배치할지를 결정하며, 기본적으로 "last"를 갖는다.
#즉 정렬된 Series는 기본적으로 마지막에 NaN값을 배치한다.
battles.sort_values(na_position = "last")

Start Date
1781-09-06    Connecticut
1779-07-05    Connecticut
1777-04-27    Connecticut
1777-09-03       Delaware
1777-05-17        Florida
                 ...
1782-08-08            NaN
1782-08-25            NaN
1782-09-13            NaN
1782-10-18            NaN
1782-12-06            NaN
Name: State, Length: 232, dtype: object

In [47]:
battles.sort_values(na_position = "first")

Start Date
1775-09-17         NaN
1775-12-31         NaN
1776-03-03         NaN
1776-03-25         NaN
1776-05-18         NaN
                ...
1781-07-06    Virginia
1781-07-01    Virginia
1781-06-26    Virginia
1781-04-25    Virginia
1783-01-22    Virginia
Name: State, Length: 232, dtype: object

In [48]:
#dropna method는 NaN값이 모두 제거된 Series를 반환한다.
#dropna()는 index label에 있는 NaN은 제거하지 않고 value쪽에 있는 NaN만 제거한다.
battles.dropna().sort_values()

Start Date
1781-09-06    Connecticut
1779-07-05    Connecticut
1777-04-27    Connecticut
1777-09-03       Delaware
1777-05-17        Florida
                 ...
1781-07-06       Virginia
1781-07-01       Virginia
1781-06-26       Virginia
1781-04-25       Virginia
1783-01-22       Virginia
Name: State, Length: 162, dtype: object

### 3.2.2 Sorting by Index with the sort_index Method

In [52]:
# The two lines below are equivalent
#index label을 기준으로 Series을 오름차순으로 정렬할 수 있다.
pokemon.sort_index()
pokemon.sort_index(ascending = True)

Pokemon
Abomasnow        Grass / Ice
Abra                 Psychic
Absol                   Dark
Accelgor                 Bug
Aegislash      Steel / Ghost
                  ...
Zoroark                 Dark
Zorua                   Dark
Zubat        Poison / Flying
Zweilous       Dark / Dragon
Zygarde      Dragon / Ground
Name: Type, Length: 809, dtype: object

In [53]:
battles.sort_index()

Start Date
1774-09-01    Massachusetts
1774-12-14    New Hampshire
1775-04-19    Massachusetts
1775-04-19    Massachusetts
1775-04-20         Virginia
                  ...
1783-01-22         Virginia
NaT              New Jersey
NaT                Virginia
NaT                     NaN
NaT                     NaN
Name: State, Length: 232, dtype: object

위 Series에서 보듯 pandas는 누락된 날짜 값 대신 다른 numpy object인 NaT를 사용한다(Null, NaN과 동일하다.).

In [55]:
#na_position매개변수로 index의 NaN값의 배치 위치를 결정한다.
battles.sort_index(na_position = "first").head()

Start Date
NaT              New Jersey
NaT                Virginia
NaT                     NaN
NaT                     NaN
1774-09-01    Massachusetts
Name: State, dtype: object

In [56]:
battles.sort_index(ascending = False).head()

Start Date
1783-01-22    Virginia
1782-12-06         NaN
1782-10-18         NaN
1782-09-13         NaN
1782-09-11    Virginia
Name: State, dtype: object

### 3.2.3 Retrieving the Smallest and Largest Values with the nsmallest and nlargest Methods

In [57]:
google.sort_values(ascending = False).head()

Date
2019-04-29    1287.58
2019-04-26    1272.18
2018-07-26    1268.33
2019-10-25    1265.13
2019-04-23    1264.55
Name: Close, dtype: float64

In [59]:
# The two lines below are equivalent

#Series object내 method중 nlargest() method는 Series에서 가장 큰 값을 반환한다.
#매개변수 n은 반환할 레코드의 개수를 설정한다.
google.nlargest(n = 5)
google.nlargest()

Date
2019-04-29    1287.58
2019-04-26    1272.18
2018-07-26    1268.33
2019-10-25    1265.13
2019-04-23    1264.55
Name: Close, dtype: float64

In [60]:
# The two lines below are equivalent

#Series object내 method중 nlargest() method는 Series에서 가장 작은 값을 반환한다.
#매개변수 n은 반환할 레코드의 개수를 설정한다.
google.nsmallest(n = 5)
google.nsmallest(5)

Date
2004-09-03    49.82
2004-09-01    49.94
2004-08-19    49.98
2004-09-02    50.57
2004-09-07    50.60
Name: Close, dtype: float64

## 3.3 Overwriting a Series with the inplace Parameter

### inplace 매개변수 사용을 권장하지 않는다.

In [61]:
battles.head(3)

Start Date
1774-09-01    Massachusetts
1774-12-14    New Hampshire
1775-04-19    Massachusetts
Name: State, dtype: object

In [62]:
battles.sort_values().head(3)

Start Date
1781-09-06    Connecticut
1779-07-05    Connecticut
1777-04-27    Connecticut
Name: State, dtype: object

In [63]:
battles.head(3)

Start Date
1774-09-01    Massachusetts
1774-12-14    New Hampshire
1775-04-19    Massachusetts
Name: State, dtype: object

In [64]:
battles.head(3)

Start Date
1774-09-01    Massachusetts
1774-12-14    New Hampshire
1775-04-19    Massachusetts
Name: State, dtype: object

In [71]:
type(battles)

pandas.core.series.Series

In [76]:
#inplace에 True을 전달하면 method가 호출되는 object를 수정하게 된다.
#이때는 battles이 오름차순으로 정렬된 형태로 수정된다.
battles.sort_values(inplace = True)

ValueError: This Series is a view of some other array, to sort in-place you must create a copy

battles이라는 object가 독립적인 Series가 아닌 DataFrame에서 파생된 Series이기 때문에 다음과 같이 이러한 파생관계를 지워야만 위 코드가 오류없이 실행시킬 수 있다.

In [77]:
battles=battles.copy()
battles.sort_values(inplace=True)

In [78]:
battles.head(3)

Start Date
1781-09-06    Connecticut
1779-07-05    Connecticut
1777-04-27    Connecticut
Name: State, dtype: object

inplace 매개변수를 사용하더라도 pandas는 method을 호출할 때마다 object의 복사본을 만든다.

inplace 매개변수를 True로 설정했을 경우 기존 변수에 새 object을 할당하는 것이므로 당연히 battles.sort_values()의 결과가 object로 메모리에 저장이 되고, 이 object가 battle에 덮어씌어 지는 것이다.


그렇기에 다음 두 코드는 기술적으로 동일하다.

In [80]:
battles.sort_values(inplace=True)
battles=battles.sort_values()  #권장

## 3.4 Counting Values with the value_counts Method

In [81]:
pokemon.head()

Pokemon
Bulbasaur     Grass / Poison
Ivysaur       Grass / Poison
Venusaur      Grass / Poison
Charmander              Fire
Charmeleon              Fire
Name: Type, dtype: object

포켓몬의 가장 흔한 유형이 뭔지 알기 위해 다음과 같이 값을 버킷으로 그룹화하고, 각 버킷의 요소 개수를 계산한다.

In [83]:
#각 Series 값의 발생 횟수를 계산하는 value_counts() method사용
#반환되는 Series의 index label은 pokemon Series의 값이고, 값은 pokemon Series의 값의 개수이다.
pokemon.value_counts()

Type
Normal                65
Water                 61
Grass                 38
Psychic               35
Fire                  30
                      ..
Fire / Psychic         1
Normal / Ground        1
Psychic / Fighting     1
Dark / Ghost           1
Fire / Ghost           1
Name: count, Length: 159, dtype: int64

In [84]:
len(pokemon.value_counts())

159

In [85]:
pokemon.nunique()

159

In [86]:
pokemon.value_counts(ascending = True)

Type
Fire / Ghost         1
Fighting / Dark      1
Fighting / Steel     1
Normal / Ground      1
Fire / Psychic       1
                    ..
Fire                30
Psychic             35
Grass               38
Water               61
Normal              65
Name: count, Length: 159, dtype: int64

In [87]:
#normalize 매개변수를 True로 설정하여 각 고유값의 빈도를 계산할 수 있다.
pokemon.value_counts(normalize = True).head()

Type
Normal     0.080346
Water      0.075402
Grass      0.046972
Psychic    0.043263
Fire       0.037083
Name: proportion, dtype: float64

In [88]:
#각 포켓몬 유형이 전체에 기여하는 비율을 얻기 위해서는 100을 곱하면된다.
pokemon.value_counts(normalize = True).head() * 100

Type
Normal     8.034611
Water      7.540173
Grass      4.697157
Psychic    4.326329
Fire       3.708282
Name: proportion, dtype: float64

In [89]:
#round()method를 사용하여 Series의 값을 반올림할 수 있다.
#decimals 매개변수는 소수점 뒤에 남겨둘 자릿수를 결정한다.
(pokemon.value_counts(normalize = True) * 100).round(2)

Type
Normal                8.03
Water                 7.54
Grass                 4.70
Psychic               4.33
Fire                  3.71
                      ...
Fire / Psychic        0.12
Normal / Ground       0.12
Psychic / Fighting    0.12
Dark / Ghost          0.12
Fire / Ghost          0.12
Name: proportion, Length: 159, dtype: float64

In [92]:
#google Series의 값이 숫자값일 때 각 숫자값의 빈도수를 값으로 갖는 Series를 반환한다.
google.value_counts().head()

Close
287.68    3
194.27    3
307.10    3
288.92    3
290.41    3
Name: count, dtype: int64

In [93]:
google.max()

1287.58

In [94]:
google.min()

49.82

In [96]:
len(google)

3824

In [97]:
google

Date
2004-08-19      49.98
2004-08-20      53.95
2004-08-23      54.50
2004-08-24      52.24
2004-08-25      52.80
               ...
2019-10-21    1246.15
2019-10-22    1242.80
2019-10-23    1259.13
2019-10-24    1260.99
2019-10-25    1265.13
Name: Close, Length: 3824, dtype: float64

In [95]:
#주가를 0에서 시작하여 최대 1,400까지 200개의 버킷으로 그룹화하겠다.
buckets = [0, 200, 400, 600, 800, 1000, 1200, 1400]
google.value_counts(bins = buckets)

(200.0, 400.0]      1568
(-0.001, 200.0]      595
(400.0, 600.0]       575
(1000.0, 1200.0]     406
(600.0, 800.0]       380
(800.0, 1000.0]      207
(1200.0, 1400.0]      93
Name: count, dtype: int64

(200.0, 400.0]       1568

200에서 400사이 주가를 갖는 날짜가 1568개였다.

In [99]:
#index label을 기준으로 오름차순으로 정렬
google.value_counts(bins = buckets).sort_index()

(-0.001, 200.0]      595
(200.0, 400.0]      1568
(400.0, 600.0]       575
(600.0, 800.0]       380
(800.0, 1000.0]      207
(1000.0, 1200.0]     406
(1200.0, 1400.0]      93
Name: count, dtype: int64

In [101]:
#sort매개변수를 False로 설정하여, 값을 내림차순으로 정렬하는 것을 막을 수 있다.
google.value_counts(bins = buckets, sort = False)

(-0.001, 200.0]      595
(200.0, 400.0]      1568
(400.0, 600.0]       575
(600.0, 800.0]       380
(800.0, 1000.0]      207
(1000.0, 1200.0]     406
(1200.0, 1400.0]      93
Name: count, dtype: int64

In [102]:
#bins매개변수에 정수 인수가 전달될 경우, 이 정수 값으로 구간이 나눠진다.
#이때 pandas는 Series의 최댓값과 최솟값의 차이를 자동으로 계산하고 범위를 지정된 수의 빈값으로 나눈다.
#즉 단순 0부터 시작하는 것이 아닌 최솟값부터 구간이 시작된다.
google.value_counts(bins = 6, sort = False)

(48.581, 256.113]      1204
(256.113, 462.407]     1104
(462.407, 668.7]        507
(668.7, 874.993]        380
(874.993, 1081.287]     292
(1081.287, 1287.58]     337
Name: count, dtype: int64

In [103]:
battles.head()

Start Date
1781-09-06    Connecticut
1779-07-05    Connecticut
1777-04-27    Connecticut
1777-09-03       Delaware
1777-05-17        Florida
Name: State, dtype: object

In [104]:
battles.value_counts().head()

State
South Carolina    31
New York          28
New Jersey        24
Virginia          21
Massachusetts     11
Name: count, dtype: int64

In [105]:
#pandas는 기본적으로 value_counts Series에서 NaN값을 제외한다.
#dropna 매개변수에 False를 전달하여 NaN값도 포함시킬 수 있다.
battles.value_counts(dropna = False).head()

State
NaN               70
South Carolina    31
New York          28
New Jersey        24
Virginia          21
Name: count, dtype: int64

In [106]:
battles.index

DatetimeIndex(['1781-09-06', '1779-07-05', '1777-04-27', '1777-09-03',
               '1777-05-17', '1779-09-10', '1779-09-07', '1780-03-02',
               '1778-06-30', '1781-01-07',
               ...
               '1782-05-06', '1782-05-25', '1782-05-28', '1782-07-01',
               '1782-07-06', '1782-08-08', '1782-08-25', '1782-09-13',
               '1782-10-18', '1782-12-06'],
              dtype='datetime64[ns]', name='Start Date', length=232, freq=None)

In [108]:
#index의 빈도수도 계산할 수 있다.
battles.index.value_counts()

Start Date
1781-09-13    2
1777-08-22    2
1775-04-19    2
1782-01-11    2
1780-08-18    2
             ..
1777-09-19    1
1777-08-16    1
1776-08-27    1
1777-10-07    1
1782-12-06    1
Name: count, Length: 217, dtype: int64

## 3.5 Invoking a Function on Every Series Value with the apply Method

파이썬에서는 함수도 다른 데이터 유형과 마찬가지로 유효한 자료구조이다.

즉 숫자로 할 수 있는 모든 것을 함수로 할 수 있다.

        함수를 리스트에 저장할 수 있다.
        dictionary key에 대한 값으로 함수를 할당할 수 있다.
        함수를 다른 함수에 인수로 전달할 수 있다.
        다른 함수에서 함수를 반환할 수 있다.

In [109]:
funcs = [len, max, min]

In [111]:
funcs = [len, max, min]

#순서대로 google Series의 행의 개수, 최댓값, 최소값을 출력하게 된다.
for current_func in funcs:
    print(current_func(google))

3824
1287.58
49.82

In [112]:
round(99.2)

99

In [113]:
round(99.49)

99

In [114]:
round(99.5)

100

In [116]:
# The two lines below are equivalent
#반올림 함수 round()를 Series의 모든 값에 적용할 수 있다.
#apply() method는 각 Series값에 대해 한 번씩 함수를 호출하고 함수 호출의 반환 값으로 구성된 새 Series를 반환한다.
google.apply(func = round)
google.apply(round)

Date
2004-08-19      50
2004-08-20      54
2004-08-23      54
2004-08-24      52
2004-08-25      53
              ...
2019-10-21    1246
2019-10-22    1243
2019-10-23    1259
2019-10-24    1261
2019-10-25    1265
Name: Close, Length: 3824, dtype: int64

In [117]:
def single_or_multi(pokemon_type):
    if "/" in pokemon_type:
        return "Multi"
    
    return "Single"

In [118]:
pokemon.head(4)

Pokemon
Bulbasaur     Grass / Poison
Ivysaur       Grass / Poison
Venusaur      Grass / Poison
Charmander              Fire
Name: Type, dtype: object

In [119]:
#사용자 정의 함수를 Series의 각 값에 적용하여, 포켓몬 타입이 여러개인지, 하나인지 확인할 수 있다.
pokemon.apply(single_or_multi)

Pokemon
Bulbasaur       Multi
Ivysaur         Multi
Venusaur        Multi
Charmander     Single
Charmeleon     Single
                ...
Stakataka       Multi
Blacephalon     Multi
Zeraora        Single
Meltan         Single
Melmetal       Single
Name: Type, Length: 809, dtype: object

In [120]:
pokemon.apply(single_or_multi).value_counts()

Type
Multi     405
Single    404
Name: count, dtype: int64

## 3.6 Coding Challenge

### 3.6.1 Problems

### 3.6.2 Solutions

In [65]:
import datetime as dt
today = dt.datetime(2020, 12, 26)
today.strftime("%A")

'Saturday'

In [66]:
pd.read_csv("revolutionary_war.csv").head()

                              Battle  Start Date          State
0                       Powder Alarm    9/1/1774  Massachusetts
1  Storming of Fort William and Mary  12/14/1774  New Hampshire
2   Battles of Lexington and Concord   4/19/1775  Massachusetts
3                    Siege of Boston   4/19/1775  Massachusetts
4                 Gunpowder Incident   4/20/1775       Virginia

In [67]:
days_of_war = pd.read_csv(
    "revolutionary_war.csv",
    usecols = ["Start Date"],
    parse_dates = ["Start Date"],
    squeeze = True,
)

days_of_war.head()

0   1774-09-01
1   1774-12-14
2   1775-04-19
3   1775-04-19
4   1775-04-20
Name: Start Date, dtype: datetime64[ns]

In [68]:
def day_of_week(date):
    return date.strftime("%A")

**NOTE**: I've commented out the code below so that the Notebook can run without raising an error.

In [69]:
# days_of_war.apply(day_of_week)

In [70]:
days_of_war.dropna().apply(day_of_week)

0       Thursday
1      Wednesday
2      Wednesday
3      Wednesday
4       Thursday
         ...
227    Wednesday
228       Friday
229       Friday
230       Friday
231    Wednesday
Name: Start Date, Length: 228, dtype: object

In [71]:
days_of_war.dropna().apply(day_of_week).value_counts()

Saturday     39
Friday       39
Wednesday    32
Sunday       31
Thursday     31
Tuesday      29
Monday       27
Name: Start Date, dtype: int64

## 3.7 Summary