Address열을 Street, City, State, Zip(도로, 시, 주 및 우편번호)이라는 네 가지 값으로 분리하고 기존 Address열을 삭제하라

In [1]:
import pandas as pd

In [16]:
customers=pd.read_csv("customers.csv")
customers

                     Name                                            Address
0           Frank Manning  6461 Quinn Groves, East Matthew, New Hampshire...
1       Elizabeth Johnson  1360 Tracey Ports Apt. 419, Kyleport, Vermont,...
2         Donald Stephens  19120 Fleming Manors, Prestonstad, Montana, 23495
3     Michael Vincent III       441 Olivia Creek, Jimmymouth, Georgia, 82991
4          Jasmine Zamora  4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...
...                   ...                                                ...
9956        Dana Browning  762 Andrew Views Apt. 254, North Paul, New Mex...
9957      Amanda Anderson  44188 Day Crest Apt. 901, Lake Marcia, Maine, ...
9958           Eric Davis  73015 Michelle Squares, Watsonville, West Virg...
9959     Taylor Hernandez       129 Keith Greens, Haleyfurt, Oklahoma, 98916
9960     Sherry Nicholson   355 Griffin Valley, Davidtown, New Mexico, 17581

[9961 rows x 2 columns]

In [4]:
customers["Address"].head().values

array(['6461 Quinn Groves, East Matthew, New Hampshire, 16656',
       '1360 Tracey Ports Apt. 419, Kyleport, Vermont, 31924',
       '19120 Fleming Manors, Prestonstad, Montana, 23495',
       '441 Olivia Creek, Jimmymouth, Georgia, 82991',
       '4246 Chelsey Ford Apt. 310, Karamouth, Utah, 76252'], dtype=object)

In [17]:
customers["Address"].str.split(", ").head()

0    [6461 Quinn Groves, East Matthew, New Hampshir...
1    [1360 Tracey Ports Apt. 419, Kyleport, Vermont...
2    [19120 Fleming Manors, Prestonstad, Montana, 2...
3       [441 Olivia Creek, Jimmymouth, Georgia, 82991]
4    [4246 Chelsey Ford Apt. 310, Karamouth, Utah, ...
Name: Address, dtype: object

In [18]:
new_dataframe=customers["Address"].str.split(pat=", ",expand=True)
new_dataframe

                               0             1              2      3
0              6461 Quinn Groves  East Matthew  New Hampshire  16656
1     1360 Tracey Ports Apt. 419      Kyleport        Vermont  31924
2           19120 Fleming Manors   Prestonstad        Montana  23495
3               441 Olivia Creek    Jimmymouth        Georgia  82991
4     4246 Chelsey Ford Apt. 310     Karamouth           Utah  76252
...                          ...           ...            ...    ...
9956   762 Andrew Views Apt. 254    North Paul     New Mexico  28889
9957    44188 Day Crest Apt. 901   Lake Marcia          Maine  37378
9958      73015 Michelle Squares   Watsonville  West Virginia  03933
9959            129 Keith Greens     Haleyfurt       Oklahoma  98916
9960          355 Griffin Valley     Davidtown     New Mexico  17581

[9961 rows x 4 columns]

In [19]:
customers[["Street","City","State","Zip"]]=new_dataframe
customers

,Name,Address,Street,City,State,Zip
0,Frank Manning,"6461 Quinn Groves, East Matthew, New Hampshire...",6461 Quinn Groves,East Matthew,New Hampshire,16656
1,Elizabeth Johnson,"1360 Tracey Ports Apt. 419, Kyleport, Vermont,...",1360 Tracey Ports Apt. 419,Kyleport,Vermont,31924
2,Donald Stephens,"19120 Fleming Manors, Prestonstad, Montana, 23495",19120 Fleming Manors,Prestonstad,Montana,23495
3,Michael Vincent III,"441 Olivia Creek, Jimmymouth, Georgia, 82991",441 Olivia Creek,Jimmymouth,Georgia,82991
4,Jasmine Zamora,"4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...",4246 Chelsey Ford Apt. 310,Karamouth,Utah,76252
...,...,...,...,...,...,...
9956,Dana Browning,"762 Andrew Views Apt. 254, North Paul, New Mex...",762 Andrew Views Apt. 254,North Paul,New Mexico,28889
9957,Amanda Anderson,"44188 Day Crest Apt. 901, Lake Marcia, Maine, ...",44188 Day Crest Apt. 901,Lake Marcia,Maine,37378
9958,Eric Davis,"73015 Michelle Squares, Watsonville, West Virg...",73015 Michelle Squares,Watsonville,West Virginia,03933
9959,Taylor Hernandez,"129 Keith Greens, Haleyfurt, Oklahoma, 98916",129 Keith Greens,Haleyfurt,Oklahoma,98916
9960,Sherry Nicholson,"355 Griffin Valley, Davidtown, New Mexico, 17581",355 Griffin Valley,Davidtown,New Mexico,17581

In [20]:
customers=customers.drop(labels=["Address"],axis="columns")
customers

,Name,Street,City,State,Zip
0,Frank Manning,6461 Quinn Groves,East Matthew,New Hampshire,16656
1,Elizabeth Johnson,1360 Tracey Ports Apt. 419,Kyleport,Vermont,31924
2,Donald Stephens,19120 Fleming Manors,Prestonstad,Montana,23495
3,Michael Vincent III,441 Olivia Creek,Jimmymouth,Georgia,82991
4,Jasmine Zamora,4246 Chelsey Ford Apt. 310,Karamouth,Utah,76252
...,...,...,...,...,...
9956,Dana Browning,762 Andrew Views Apt. 254,North Paul,New Mexico,28889
9957,Amanda Anderson,44188 Day Crest Apt. 901,Lake Marcia,Maine,37378
9958,Eric Davis,73015 Michelle Squares,Watsonville,West Virginia,03933
9959,Taylor Hernandez,129 Keith Greens,Haleyfurt,Oklahoma,98916
9960,Sherry Nicholson,355 Griffin Valley,Davidtown,New Mexico,17581