## 6.1 Letter Casing and Whitespace

In [1]:
import pandas as pd

In [42]:
inspections = pd.read_csv("chicago_food_inspections.csv")
inspections

                                      Name             Risk
0               MARRIOT MARQUIS CHICAGO       Risk 1 (High)
1                              JETS PIZZA   Risk 2 (Medium)
2                               ROOM 1520      Risk 3 (Low)
3                MARRIOT MARQUIS CHICAGO      Risk 1 (High)
4                            CHARTWELLS       Risk 1 (High)
...                                    ...              ...
153805                         WOLCOTT'S      Risk 1 (High)
153806     DUNKIN DONUTS/BASKIN-ROBBINS     Risk 2 (Medium)
153807                           Cafe 608     Risk 1 (High)
153808                        mr.daniel's     Risk 1 (High)
153809                         TEMPO CAFE     Risk 1 (High)

[153810 rows x 2 columns]

In [3]:
inspections["Name"].head()

0     MARRIOT MARQUIS CHICAGO
1                    JETS PIZZA
2                     ROOM 1520
3      MARRIOT MARQUIS CHICAGO
4                  CHARTWELLS
Name: Name, dtype: object

In [5]:
#이렇게 확인하니 이름 값의 끝과 시작 부분에 공백이 존재한다는 것을 알 수 있다.
inspections["Name"].head().values

array([' MARRIOT MARQUIS CHICAGO   ', ' JETS PIZZA ', '   ROOM 1520 ',
       '  MARRIOT MARQUIS CHICAGO  ', ' CHARTWELLS   '], dtype=object)

문자열을 조작하고 싶을 때마다 Series자체가 아닌 StringMethods object의 method를 호출하는 것이 좋다.

Series object의 str속성을 사용하면 StringMethods object에 접근할 수 있다.

In [6]:
inspections["Name"].str

In [8]:
#lstrip()은 문자열의 시작 부분에서 공백을 제거한다.
dessert = "  cheesecake  "
print(type(dessert))
dessert.lstrip()

<class 'str'>

'cheesecake  '

In [9]:
#rstrip()은 문자열 끝에서 공백을 제거한다.
dessert.rstrip()

'  cheesecake'

In [10]:
#strip()은 문자열의 양쪽 끝에서 공백을 제거한다.
dessert.strip()

'cheesecake'

In [11]:
#lstrip()은 Name Series의 모든 값에 적용된다.
inspections["Name"].str.lstrip().head()

0    MARRIOT MARQUIS CHICAGO
1                   JETS PIZZA
2                    ROOM 1520
3     MARRIOT MARQUIS CHICAGO
4                 CHARTWELLS
Name: Name, dtype: object

In [12]:
inspections["Name"].str.rstrip().head()

0      MARRIOT MARQUIS CHICAGO
1                   JETS PIZZA
2                    ROOM 1520
3      MARRIOT MARQUIS CHICAGO
4                   CHARTWELLS
Name: Name, dtype: object

In [13]:
inspections["Name"].str.strip().head()

0    MARRIOT MARQUIS CHICAGO
1                 JETS PIZZA
2                  ROOM 1520
3    MARRIOT MARQUIS CHICAGO
4                 CHARTWELLS
Name: Name, dtype: object

In [15]:
#각 값마다 공백이 모두 없어진 것을 확인할 수 있다.
inspections["Name"].str.strip().head().values

array(['MARRIOT MARQUIS CHICAGO', 'JETS PIZZA', 'ROOM 1520',
       'MARRIOT MARQUIS CHICAGO', 'CHARTWELLS'], dtype=object)

In [37]:
inspections["Name"] = inspections["Name"].str.strip()

In [17]:
inspections.columns

Index(['Name', 'Risk'], dtype='object')

In [43]:
#DataFrame의 모든 열에 대해 strip()로 각 값에 존재하는 공백을 제거한다.
for column in inspections.columns:
    inspections[column] = inspections[column].str.strip()

In [19]:
#lower()로 문자열의 모든 문자를 소문자로 변환한다.
inspections["Name"].str.lower().head()

0    marriot marquis chicago
1                 jets pizza
2                  room 1520
3    marriot marquis chicago
4                 chartwells
Name: Name, dtype: object

In [20]:
steaks = pd.Series(["porterhouse", "filet mignon", "ribeye"])
steaks

0     porterhouse
1    filet mignon
2          ribeye
dtype: object

In [22]:
#upper()은 문자열의 모든 문자를 대문자로 변환한다.
steaks.str.upper()

0     PORTERHOUSE
1    FILET MIGNON
2          RIBEYE
dtype: object

In [24]:
#capitalize() method는 Series에서 각 문자열의 첫 번째 문자만 대문자로 표시한다.
inspections["Name"].str.capitalize().head()

0    Marriot marquis chicago
1                 Jets pizza
2                  Room 1520
3    Marriot marquis chicago
4                 Chartwells
Name: Name, dtype: object

In [25]:
#title()는 문자열 내 각 단어의 첫 번째 문자만 대문자로 표시한다.
inspections["Name"].str.title().head()

0    Marriot Marquis Chicago
1                 Jets Pizza
2                  Room 1520
3    Marriot Marquis Chicago
4                 Chartwells
Name: Name, dtype: object

## 6.2 String Slicing

In [26]:
inspections["Risk"].head()

0      Risk 1 (High)
1    Risk 2 (Medium)
2       Risk 3 (Low)
3      Risk 1 (High)
4      Risk 1 (High)
Name: Risk, dtype: object

In [27]:
len(inspections)

153810

In [28]:
#Risk Series의 고유한 값을 배열로써 나타내는 unique()로 확인한 결과
#이 Series는 결측값(NaN)과 ALL문자열이라는 예상하지 못한 형식도 포함하고 있는 것을 알 수 있다.
inspections["Risk"].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)', 'All', nan],
      dtype=object)

In [44]:
#Risk Series에서 결측값을 갖는 행을 제거한다.
inspections = inspections.dropna(subset = ["Risk"])

In [30]:
inspections["Risk"].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)', 'All'],
      dtype=object)

In [45]:
#replace()는 DataFrame내 to_replace에 대한 값을 value값으로 치환하는 method이다.
inspections["Risk"] = inspections["Risk"].replace(
    to_replace = "All", value = "Risk 4 (Extreme)"
)

/var/folders/g2/m_rjbg_d4fq330k9g6z2v24m0000gn/T/ipykernel_1239/591377566.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inspections["Risk"] = inspections["Risk"].replace(

In [46]:
inspections["Risk"].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)',
       'Risk 4 (Extreme)'], dtype=object)

### 6.3 String Slicing and Character Replacement

StringMethods object의 slice()를 사용하면 index 위치를 기반으로 문자열에서 하위 문자열을 추출할 수 있다.

이 method는 시작 index와 끝 index를 인수로 받는다.

In [47]:
#Risk 3과 같이 "Risk "뒤 위험도 숫자에 대한 문자를 가져온다.
inspections["Risk"].str.slice(5, 6).head()

0    1
1    2
2    3
3    1
4    1
Name: Risk, dtype: object

In [48]:
#python의 list slicing구문으로 동일하게 구현할 수도 있다.
inspections["Risk"].str[5:6].head()

0    1
1    2
2    3
3    1
4    1
Name: Risk, dtype: object

In [49]:
#slice()에 단일 값을 전달하면 pandas는 이를 하한값으로 사용하고, 문자열 끝까지 추출한다.
inspections["Risk"].str.slice(8).head()

0      High)
1    Medium)
2       Low)
3      High)
4      High)
Name: Risk, dtype: object

In [50]:
inspections["Risk"].str[8:].head()

0      High)
1    Medium)
2       Low)
3      High)
4      High)
Name: Risk, dtype: object

In [51]:
#문자열 끝을 기준으로 잡아 index 경계를 설정한다.
inspections["Risk"].str.slice(8, -1).head()

0      High
1    Medium
2       Low
3      High
4      High
Name: Risk, dtype: object

In [52]:
inspections["Risk"].str[8:-1].head()

0      High
1    Medium
2       Low
3      High
4      High
Name: Risk, dtype: object

In [53]:
#replace()를 사용하여 )를 빈 문자열로 치환한다.
inspections["Risk"].str.slice(8).str.replace(")", "").head()

0      High
1    Medium
2       Low
3      High
4      High
Name: Risk, dtype: object

## 6.3 Boolean Methods

In [54]:
"Pizza" in "Jets Pizza"

True

In [55]:
"pizza" in "Jets Pizza"

False

In [57]:
#일단 모든 열 값을 소문자로 변환한다. 그리고 소문자 단어 pizza를 찾는다.
#contains()는 각 Series 값에 하위 문자열이 포함되어 있는지 확인한다.
inspections["Name"].str.lower().str.contains("pizza").head()

0    False
1     True
2    False
3    False
4    False
Name: Name, dtype: bool

In [59]:
#Name Series 중 Pizza가 포함된 모든 행을 추출한다.
has_pizza = inspections["Name"].str.lower().str.contains("pizza")
inspections[has_pizza]

                                    Name             Risk
1                             JETS PIZZA  Risk 2 (Medium)
19         NANCY'S HOME OF STUFFED PIZZA    Risk 1 (High)
27            NARY'S GRILL & PIZZA ,INC.    Risk 1 (High)
29                   NARYS GRILL & PIZZA    Risk 1 (High)
68                         COLUTAS PIZZA    Risk 1 (High)
...                                  ...              ...
153756       ANGELO'S STUFFED PIZZA CORP    Risk 1 (High)
153764                COCHIAROS PIZZA #2    Risk 1 (High)
153772  FERNANDO'S MEXICAN GRILL & PIZZA    Risk 1 (High)
153788            REGGIO'S PIZZA EXPRESS    Risk 1 (High)
153801        State Street Pizza Company    Risk 1 (High)

[3992 rows x 2 columns]

In [60]:
#startswith()는 문자열이 인수로 주어진 문자열로 시작하면 True로 반환하는 method이다.
#이때는 tacos로 시작하는 행을 추출한다.
inspections["Name"].str.lower().str.startswith("tacos").head()

0    False
1    False
2    False
3    False
4    False
Name: Name, dtype: bool

In [61]:
starts_with_tacos = (
    inspections["Name"].str.lower().str.startswith("tacos")
)
inspections[starts_with_tacos]

                         Name           Risk
69               TACOS NIETOS  Risk 1 (High)
556       TACOS EL TIO 2 INC.  Risk 1 (High)
675          TACOS DON GABINO  Risk 1 (High)
958       TACOS EL TIO 2 INC.  Risk 1 (High)
1036      TACOS EL TIO 2 INC.  Risk 1 (High)
...                       ...            ...
143587          TACOS DE LUNA  Risk 1 (High)
144026           TACOS GARCIA  Risk 1 (High)
146174        Tacos Place's 1  Risk 1 (High)
147810  TACOS MARIO'S LIMITED  Risk 1 (High)
151191            TACOS REYNA  Risk 1 (High)

[105 rows x 2 columns]

In [62]:
#endswith()는 인수로 주어진 문자열이 문자열의 끝에 있는지 확인하는 method이다.
ends_with_tacos = (
    inspections["Name"].str.lower().str.endswith("tacos")
)
inspections[ends_with_tacos]

                   Name           Risk
382        LAZO'S TACOS  Risk 1 (High)
569        LAZO'S TACOS  Risk 1 (High)
2652       FLYING TACOS   Risk 3 (Low)
3250       JONY'S TACOS  Risk 1 (High)
3812       PACO'S TACOS  Risk 1 (High)
...                 ...            ...
151121      REYES TACOS  Risk 1 (High)
151318   EL MACHO TACOS  Risk 1 (High)
151801   EL MACHO TACOS  Risk 1 (High)
153087  RAYMOND'S TACOS  Risk 1 (High)
153504        MIS TACOS  Risk 1 (High)

[304 rows x 2 columns]

## 6.4 Splitting Strings

In [84]:
customers = pd.read_csv("customers.csv")
customers.head()

                  Name                                            Address
0        Frank Manning  6461 Quinn Groves, East Matthew, New Hampshire...
1    Elizabeth Johnson  1360 Tracey Ports Apt. 419, Kyleport, Vermont,...
2      Donald Stephens  19120 Fleming Manors, Prestonstad, Montana, 23495
3  Michael Vincent III       441 Olivia Creek, Jimmymouth, Georgia, 82991
4       Jasmine Zamora  4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...

In [85]:
#str.len()를 사용하여 각 행의 문자열 길이를 반환한다.
customers["Name"].str.len().head()

0    13
1    17
2    15
3    19
4    14
Name: Name, dtype: int64

In [86]:
#split()는 인자로 주어진 기호를 사용하여 문자열을 분할하는 method이다.
phone_number = "555-123-4567"
phone_number.split("-")

['555', '123', '4567']

In [87]:
#각 문자열에서 공백을 기준으로 값을 분할한다.
# The two lines below are equivalent
customers["Name"].str.split(pat = " ").head()
customers["Name"].str.split(" ").head()

0           [Frank, Manning]
1       [Elizabeth, Johnson]
2         [Donald, Stephens]
3    [Michael, Vincent, III]
4          [Jasmine, Zamora]
Name: Name, dtype: object

In [88]:
#각 문자열을 공백을 기준으로 값을 분할했을 때 그 결과로 나온 list의 길이를 살펴본다.
customers["Name"].str.split(" ").str.len().head()

0    2
1    2
2    2
3    3
4    2
Name: Name, dtype: int64

In [89]:
#분할의 최대 임계값을 1로 설정하여 첫 번째 공백에서 문자열을 분할하고 중지하도록 한다. 
customers["Name"].str.split(pat = " ", n = 1).head()

0          [Frank, Manning]
1      [Elizabeth, Johnson]
2        [Donald, Stephens]
3    [Michael, Vincent III]
4         [Jasmine, Zamora]
Name: Name, dtype: object

In [90]:
#str.get()을 사용하여 문자열 list내 index 위치를 기반으로 값을 가져올 수 있다.
#다음은 index 0을 대상으로 지정하여 각 list의 첫 번째 요소를 추출한다.
customers["Name"].str.split(pat = " ", n = 1).str.get(0).head()

0        Frank
1    Elizabeth
2       Donald
3      Michael
4      Jasmine
Name: Name, dtype: object

In [91]:
customers["Name"].str.split(pat = " ", n = 1).str.get(1).head()

0        Manning
1        Johnson
2       Stephens
3    Vincent III
4         Zamora
Name: Name, dtype: object

In [92]:
customers["Name"].str.split(pat = " ", n = 1).str.get(-1).head()

0        Manning
1        Johnson
2       Stephens
3    Vincent III
4         Zamora
Name: Name, dtype: object

In [93]:
#expand매개변수에 True를 전달하여 문자열 list를 행으로 갖는 Series가 아닌 DataFrame으로 결과를 반환한다.
customers["Name"].str.split(
    pat = " ", n = 1, expand = True
).head()

           0            1
0      Frank      Manning
1  Elizabeth      Johnson
2     Donald     Stephens
3    Michael  Vincent III
4    Jasmine       Zamora

In [94]:
#index 2를 보면 알 수 있듯이 pandas는 요소가 불충분한 행에는 None값을 배치한다.
customers["Name"].str.split(pat = " ", expand = True).head()

           0         1     2
0      Frank   Manning  None
1  Elizabeth   Johnson  None
2     Donald  Stephens  None
3    Michael   Vincent   III
4    Jasmine    Zamora  None

In [95]:
#기존 DataFrame에 새로운 2열 DataFrame을 연결한다.
customers[["First Name", "Last Name"]] = customers[
    "Name"
].str.split(pat = " ", n = 1, expand = True)

In [96]:
customers

,Name,Address,First Name,Last Name
0,Frank Manning,"6461 Quinn Groves, East Matthew, New Hampshire...",Frank,Manning
1,Elizabeth Johnson,"1360 Tracey Ports Apt. 419, Kyleport, Vermont,...",Elizabeth,Johnson
2,Donald Stephens,"19120 Fleming Manors, Prestonstad, Montana, 23495",Donald,Stephens
3,Michael Vincent III,"441 Olivia Creek, Jimmymouth, Georgia, 82991",Michael,Vincent III
4,Jasmine Zamora,"4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...",Jasmine,Zamora
...,...,...,...,...
9956,Dana Browning,"762 Andrew Views Apt. 254, North Paul, New Mex...",Dana,Browning
9957,Amanda Anderson,"44188 Day Crest Apt. 901, Lake Marcia, Maine, ...",Amanda,Anderson
9958,Eric Davis,"73015 Michelle Squares, Watsonville, West Virg...",Eric,Davis
9959,Taylor Hernandez,"129 Keith Greens, Haleyfurt, Oklahoma, 98916",Taylor,Hernandez
9960,Sherry Nicholson,"355 Griffin Valley, Davidtown, New Mexico, 17581",Sherry,Nicholson

In [97]:
#기존에 있던 Name 열을 삭제한다.
customers = customers.drop(labels = "Name", axis = "columns")

In [98]:
customers.head()

                                             Address First Name    Last Name
0  6461 Quinn Groves, East Matthew, New Hampshire...      Frank      Manning
1  1360 Tracey Ports Apt. 419, Kyleport, Vermont,...  Elizabeth      Johnson
2  19120 Fleming Manors, Prestonstad, Montana, 23495     Donald     Stephens
3       441 Olivia Creek, Jimmymouth, Georgia, 82991    Michael  Vincent III
4  4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...    Jasmine       Zamora

## 6.5 Coding Challenge

### 6.5.1 Problems

### 6.5.2 Solutions

In [99]:
customers["Address"].str.split(",").head()

0    [6461 Quinn Groves,  East Matthew,  New Hampsh...
1    [1360 Tracey Ports Apt. 419,  Kyleport,  Vermo...
2    [19120 Fleming Manors,  Prestonstad,  Montana,...
3    [441 Olivia Creek,  Jimmymouth,  Georgia,  82991]
4    [4246 Chelsey Ford Apt. 310,  Karamouth,  Utah...
Name: Address, dtype: object

In [100]:
customers["Address"].str.split(", ").head()

0    [6461 Quinn Groves, East Matthew, New Hampshir...
1    [1360 Tracey Ports Apt. 419, Kyleport, Vermont...
2    [19120 Fleming Manors, Prestonstad, Montana, 2...
3       [441 Olivia Creek, Jimmymouth, Georgia, 82991]
4    [4246 Chelsey Ford Apt. 310, Karamouth, Utah, ...
Name: Address, dtype: object

In [101]:
customers["Address"].str.split(", ", expand = True).head()

                            0             1              2      3
0           6461 Quinn Groves  East Matthew  New Hampshire  16656
1  1360 Tracey Ports Apt. 419      Kyleport        Vermont  31924
2        19120 Fleming Manors   Prestonstad        Montana  23495
3            441 Olivia Creek    Jimmymouth        Georgia  82991
4  4246 Chelsey Ford Apt. 310     Karamouth           Utah  76252

In [102]:
new_cols = ["Street", "City", "State", "Zip"]

customers[new_cols] = customers["Address"].str.split(
    pat = ", ", expand = True
)

In [103]:
customers.drop(labels = "Address", axis = "columns").head()

,First Name,Last Name,Street,City,State,Zip
0,Frank,Manning,6461 Quinn Groves,East Matthew,New Hampshire,16656
1,Elizabeth,Johnson,1360 Tracey Ports Apt. 419,Kyleport,Vermont,31924
2,Donald,Stephens,19120 Fleming Manors,Prestonstad,Montana,23495
3,Michael,Vincent III,441 Olivia Creek,Jimmymouth,Georgia,82991
4,Jasmine,Zamora,4246 Chelsey Ford Apt. 310,Karamouth,Utah,76252

In [104]:
del customers["Address"]

In [105]:
customers.tail()

,First Name,Last Name,Street,City,State,Zip
9956,Dana,Browning,762 Andrew Views Apt. 254,North Paul,New Mexico,28889
9957,Amanda,Anderson,44188 Day Crest Apt. 901,Lake Marcia,Maine,37378
9958,Eric,Davis,73015 Michelle Squares,Watsonville,West Virginia,03933
9959,Taylor,Hernandez,129 Keith Greens,Haleyfurt,Oklahoma,98916
9960,Sherry,Nicholson,355 Griffin Valley,Davidtown,New Mexico,17581

## 6.6 A Note on Regular Expressions

Regular Expressions은 문자열 내에서 일련의 문자를 찾는 검색 패턴이다.

In [106]:
customers["Street"].head()

0             6461 Quinn Groves
1    1360 Tracey Ports Apt. 419
2          19120 Fleming Manors
3              441 Olivia Creek
4    4246 Chelsey Ford Apt. 310
Name: Street, dtype: object

In [107]:
#Street열에 replace()를 사용하여 4자리 숫자의 모든 항목을 별표 문자로 치환한다.
customers["Street"].str.replace(
    "\d{4,}", "*", regex = True
).head()

0             * Quinn Groves
1    * Tracey Ports Apt. 419
2           * Fleming Manors
3           441 Olivia Creek
4    * Chelsey Ford Apt. 310
Name: Street, dtype: object

## 6.7 Summary