## 5.1 Optimizing A Data Set for Memory Usage

In [1]:
import pandas as pd

In [2]:
pd.read_csv("employees.csv")

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male     8/6/93       NaN   True     Marketing
1        Thomas    Male    3/31/96   61933.0   True           NaN
2         Maria  Female        NaN  130590.0  False       Finance
3         Jerry     NaN     3/4/05  138705.0   True       Finance
4         Larry    Male    1/24/98  101004.0   True            IT
...         ...     ...        ...       ...    ...           ...
996     Phillip    Male    1/31/84   42392.0  False       Finance
997     Russell    Male    5/20/13   96914.0  False       Product
998       Larry    Male    4/20/13   60500.0  False  Business Dev
999      Albert    Male    5/15/12  129949.0   True         Sales
1000        NaN     NaN        NaN       NaN    NaN           NaN

[1001 rows x 6 columns]

In [3]:
pd.read_csv("employees.csv", parse_dates = ["Start Date"]).head()

/var/folders/g2/m_rjbg_d4fq330k9g6z2v24m0000gn/T/ipykernel_995/3587683604.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.read_csv("employees.csv", parse_dates = ["Start Date"]).head()

  First Name  Gender Start Date    Salary   Mgmt       Team
0    Douglas    Male 1993-08-06       NaN   True  Marketing
1     Thomas    Male 1996-03-31   61933.0   True        NaN
2      Maria  Female        NaT  130590.0  False    Finance
3      Jerry     NaN 2005-03-04  138705.0   True    Finance
4      Larry    Male 1998-01-24  101004.0   True         IT

In [4]:
employees = pd.read_csv(
    "employees.csv", parse_dates = ["Start Date"]
)

/var/folders/g2/m_rjbg_d4fq330k9g6z2v24m0000gn/T/ipykernel_995/3313717471.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  employees = pd.read_csv(

In [5]:
#DataFrame의 각 열의 데이터 유형, 결측값의 개수를 목록으로 확인할 수 있는 method
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      999 non-null    float64
 4   Mgmt        933 non-null    object
 5   Team        957 non-null    object
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 47.1+ KB

### 5.1.1 Converting Data Types with the astype Method

In [6]:
#astype() method는 Series의 값을 다른 data type으로 변환한다. 인자로는 새로운 data type이다.
employees["Mgmt"].astype(bool)

0        True
1        True
2       False
3        True
4        True
        ...
996     False
997     False
998     False
999      True
1000     True
Name: Mgmt, Length: 1001, dtype: bool

In [7]:
#data type또는 그 이름을 나타내는 문자열 둘 중 하나를 인자로 전달한다.
#boolean type으로 변환시 NaN도 True로 반환된다.
employees["Mgmt"].astype("bool")

0        True
1        True
2       False
3        True
4        True
        ...
996     False
997     False
998     False
999      True
1000     True
Name: Mgmt, Length: 1001, dtype: bool

In [9]:
#DataFrame에서 Mgmt열을 새로운 Series로 덮어씌운다.
#만약 DataFrame에서 Mgmt열이 없다면 그 이름을 갖는 새 Series를 생성하고, DataFrame의 오른쪽에 추가한다.
employees["Mgmt"] = employees["Mgmt"].astype(bool)

In [10]:
#copy() method로 employees가 가리키는 DataFrame과 같은 DataFrame을 새로 만들고 examples이 이를 가리키도록 한다.
#만약 examples=employees로 할 경우 examples과 employees는 같은 DataFrame을 가리키게 된다.
examples=employees.copy()
examples

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       NaN   True     Marketing
1        Thomas    Male 1996-03-31   61933.0   True           NaN
2         Maria  Female        NaT  130590.0  False       Finance
3         Jerry     NaN 2005-03-04  138705.0   True       Finance
4         Larry    Male 1998-01-24  101004.0   True            IT
...         ...     ...        ...       ...    ...           ...
996     Phillip    Male 1984-01-31   42392.0  False       Finance
997     Russell    Male 2013-05-20   96914.0  False       Product
998       Larry    Male 2013-04-20   60500.0  False  Business Dev
999      Albert    Male 2012-05-15  129949.0   True         Sales
1000        NaN     NaN        NaT       NaN   True           NaN

[1001 rows x 6 columns]

In [11]:
examples["New"]=employees["Mgmt"].astype(bool)
examples

     First Name  Gender Start Date    Salary   Mgmt          Team    New
0       Douglas    Male 1993-08-06       NaN   True     Marketing   True
1        Thomas    Male 1996-03-31   61933.0   True           NaN   True
2         Maria  Female        NaT  130590.0  False       Finance  False
3         Jerry     NaN 2005-03-04  138705.0   True       Finance   True
4         Larry    Male 1998-01-24  101004.0   True            IT   True
...         ...     ...        ...       ...    ...           ...    ...
996     Phillip    Male 1984-01-31   42392.0  False       Finance  False
997     Russell    Male 2013-05-20   96914.0  False       Product  False
998       Larry    Male 2013-04-20   60500.0  False  Business Dev  False
999      Albert    Male 2012-05-15  129949.0   True         Sales   True
1000        NaN     NaN        NaT       NaN   True           NaN   True

[1001 rows x 7 columns]

In [12]:
employees.tail()

     First Name Gender Start Date    Salary   Mgmt          Team
996     Phillip   Male 1984-01-31   42392.0  False       Finance
997     Russell   Male 2013-05-20   96914.0  False       Product
998       Larry   Male 2013-04-20   60500.0  False  Business Dev
999      Albert   Male 2012-05-15  129949.0   True         Sales
1000        NaN    NaN        NaT       NaN   True           NaN

In [13]:
#Mgmt의 datatype을 문자열(object)에서 boolean으로 바꾼 것만으로도 메모리 사용량을 15%나 줄일 수 있었다.
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      999 non-null    float64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    object
dtypes: bool(1), datetime64[ns](1), float64(1), object(3)
memory usage: 40.2+ KB

**NOTE**: I've commented out the code below so that the Notebook can run without raising an error.

In [14]:
employees["Salary"].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

pandas는 NaN값을 정수로 변환할 수 없다. 그렇기에 Salary열도 astype(int)로 int형으로 변환할 수 없다.

이때는 NaN값을 상수 값으로 대체하면 된다. 

fillna()는 Series의 Null값을 사용자가 전달한 인수로 대체한다.

In [15]:
employees["Salary"].tail()

996      42392.0
997      96914.0
998      60500.0
999     129949.0
1000         NaN
Name: Salary, dtype: float64

In [16]:
#이때는 Null값을 0으로 치환한다.
employees["Salary"].fillna(0).tail()

996      42392.0
997      96914.0
998      60500.0
999     129949.0
1000         0.0
Name: Salary, dtype: float64

In [17]:
#이때는 Null값을 100으로 치환한다.
employees["Salary"].fillna(100).tail()

996      42392.0
997      96914.0
998      60500.0
999     129949.0
1000       100.0
Name: Salary, dtype: float64

In [18]:
#이제 결측값이 0으로 변환되었기에 astype()로 int형으로 변환할 수 있다.
employees["Salary"].fillna(0).astype(int).tail()

996      42392
997      96914
998      60500
999     129949
1000         0
Name: Salary, dtype: int64

In [19]:
employees["Salary"] = employees["Salary"].fillna(0).astype(int)

In [20]:
#DataFrame의 열의 고유한 값의 개수를 센다(NaN은 제외).
employees.nunique()

First Name    200
Gender          2
Start Date    971
Salary        995
Mgmt            2
Team           10
dtype: int64

#### pandas에는 category라는 data type이 있다.

In [21]:
#200개의 이름을 고유한 범주로써 식별한다.
employees["First Name"].astype("category")

0       Douglas
1        Thomas
2         Maria
3         Jerry
4         Larry
         ...
996     Phillip
997     Russell
998       Larry
999      Albert
1000        NaN
Name: First Name, Length: 1001, dtype: category
Categories (200, object): ['Aaron', 'Adam', 'Alan', 'Albert', ..., 'Wanda', 'Wayne', 'William', 'Willie']

In [22]:
#두 가지 고유한 범주를 식별한다.
employees["Gender"].astype("category")

0         Male
1         Male
2       Female
3          NaN
4         Male
         ...
996       Male
997       Male
998       Male
999       Male
1000       NaN
Name: Gender, Length: 1001, dtype: category
Categories (2, object): ['Female', 'Male']

In [23]:
employees["Gender"] = employees["Gender"].astype("category")

In [24]:
#gender의 data type을 category로 바꿨을 때 1001개의 값 대신 2개의 값만 저장하기 때문에 메모리 사용량이 약 15%줄었다.
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    category
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      1001 non-null   int64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    object
dtypes: bool(1), category(1), datetime64[ns](1), int64(1), object(2)
memory usage: 33.5+ KB

In [25]:
employees["Team"] = employees["Team"].astype("category")

In [26]:
#Team도 1001개의 값 대신 10개의 값만 저장하기 때문에 메모리 사용량이 약 20%줄었다.
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    category
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      1001 non-null   int64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    category
dtypes: bool(1), category(2), datetime64[ns](1), int64(1), object(1)
memory usage: 27.0+ KB

First Name은 category형으로 영구적으로 바꾸지 않은 이유는 data가 추가됨에 따라 First Name의 범주가 200개에서 더 증가할 수 있기 때문이다.

하지만 Gender는 남,여 2가지로 반 고정이고

팀 이름 또한 10가지로 반 고정이다. 그렇기에 데이터가 추가되어도(행이 추가되어도) 이들의 범주는 늘어나지 않을 것이기 때문에 category형으로 설정하는 것이 의미가 있다.

## 5.2 Filtering by a Single Condition

In [27]:
"Maria" == "Maria"

True

In [28]:
"Maria" == "Taylor"

False

In [29]:
#First Name에 대한 Series내 각 value와 Maria를 하나하나 비교연산한다.
employees["First Name"] == "Maria"

0       False
1       False
2        True
3       False
4       False
        ...
996     False
997     False
998     False
999     False
1000    False
Name: First Name, Length: 1001, dtype: bool

In [42]:
#위 결과에서 True값의 행을 employees DataFrame에서 추출할 수 있다.
#이는 일종의 filtering이다(boolean Series를 생성하여 이를 통해 DataFrame을 filtering한다.).
#First Name이 Maria인 행만 추출된 것을 볼 수 있다.
employees[employees["First Name"] == "Maria"]

    First Name  Gender Start Date  Salary   Mgmt          Team
2        Maria  Female        NaT  130590  False       Finance
198      Maria  Female 1990-12-27   36067   True       Product
815      Maria     NaN 1986-01-18  106562  False            HR
844      Maria     NaN 1985-06-19  148857  False         Legal
936      Maria  Female 2003-03-14   96250  False  Business Dev
984      Maria  Female 2011-10-15   43455  False   Engineering

In [32]:
#위 코드와 동일한 기능을 한다.
marias = employees["First Name"] == "Maria"
employees[marias]

    First Name  Gender Start Date  Salary   Mgmt          Team
2        Maria  Female        NaT  130590  False       Finance
198      Maria  Female 1990-12-27   36067   True       Product
815      Maria     NaN 1986-01-18  106562  False            HR
844      Maria     NaN 1985-06-19  148857  False         Legal
936      Maria  Female 2003-03-14   96250  False  Business Dev
984      Maria  Female 2011-10-15   43455  False   Engineering

In [33]:
"Finance" != "Engineering"

True

In [34]:
employees["Team"] != "Finance"

0        True
1        True
2       False
3       False
4        True
        ...
996     False
997      True
998      True
999      True
1000     True
Name: Team, Length: 1001, dtype: bool

In [37]:
#Team Series중 Finance가 아닌 팀만 추출한다.
#이때 NaN도 "Finance"문자열과 같지 않다고 간주한다.
employees[employees["Team"] != "Finance"]

     First Name  Gender Start Date  Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       0   True     Marketing
1        Thomas    Male 1996-03-31   61933   True           NaN
4         Larry    Male 1998-01-24  101004   True            IT
5        Dennis    Male 1987-04-18  115163  False         Legal
6          Ruby  Female 1987-08-17   65476   True       Product
...         ...     ...        ...     ...    ...           ...
995       Henry     NaN 2014-11-23  132483  False  Distribution
997     Russell    Male 2013-05-20   96914  False       Product
998       Larry    Male 2013-04-20   60500  False  Business Dev
999      Albert    Male 2012-05-15  129949   True         Sales
1000        NaN     NaN        NaT       0   True           NaN

[899 rows x 6 columns]

In [38]:
#Mgmt Series는 data type이 이미 boolean이므로 True값을 갖는 행만 추출할 수 있다.
employees[employees["Mgmt"]].head()

  First Name  Gender Start Date  Salary  Mgmt       Team
0    Douglas    Male 1993-08-06       0  True  Marketing
1     Thomas    Male 1996-03-31   61933  True        NaN
3      Jerry     NaN 2005-03-04  138705  True    Finance
4      Larry    Male 1998-01-24  101004  True         IT
6       Ruby  Female 1987-08-17   65476  True    Product

In [40]:
#Salary Series에서 100000이상의 값을 갖는 행만 추출한다.
high_earners = employees["Salary"] > 100000
high_earners.head()

0    False
1    False
2     True
3     True
4     True
Name: Salary, dtype: bool

In [41]:
employees[high_earners].head()

  First Name  Gender Start Date  Salary   Mgmt          Team
2      Maria  Female        NaT  130590  False       Finance
3      Jerry     NaN 2005-03-04  138705   True       Finance
4      Larry    Male 1998-01-24  101004   True            IT
5     Dennis    Male 1987-04-18  115163  False         Legal
9    Frances  Female 2002-08-08  139852   True  Business Dev

## 5.3 Filtering by Multiple Conditions

2개의 독립적인 boolean Series를 만든 다음 두 Series사이에 적용해야 하는 논리적 기준을 선언하여 DataFrame을 filtering 할 수 있다.

### 5.3.1 The AND Condition

In [43]:
is_female = employees["Gender"] == "Female"

In [44]:
in_biz_dev = employees["Team"] == "Business Dev"

In [48]:
(is_female & in_biz_dev).head(10)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9     True
dtype: bool

In [49]:
#위 두 boolean Series가 모두 만족(True)되는 행만 추출하도록 한다.  
employees[is_female & in_biz_dev].head()

   First Name  Gender Start Date  Salary   Mgmt          Team
9     Frances  Female 2002-08-08  139852   True  Business Dev
33       Jean  Female 1993-12-18  119082  False  Business Dev
36     Rachel  Female 2009-02-16  142032  False  Business Dev
38  Stephanie  Female 1986-09-13   36844   True  Business Dev
61     Denise  Female 2001-11-06  106862  False  Business Dev

In [50]:
#2개 이상의 boolean Series를 만족(True)하는 행만을 추출할 수도 있다.
is_manager = employees["Mgmt"]
employees[is_female & in_biz_dev & is_manager].head()

    First Name  Gender Start Date  Salary  Mgmt          Team
9      Frances  Female 2002-08-08  139852  True  Business Dev
38   Stephanie  Female 1986-09-13   36844  True  Business Dev
66       Nancy  Female 2012-12-15  125250  True  Business Dev
92       Linda  Female 2000-05-25  119009  True  Business Dev
111     Bonnie  Female 1999-12-17   42153  True  Business Dev

### 5.3.2 The OR Condition

In [51]:
earning_below_40k = employees["Salary"] < 40000
started_after_2015 = employees["Start Date"] > "2015-01-01"

In [54]:
#Salary가 40000미만이거나, Start date이 2015년 1월 1일 이후인 모든 직원을 식별
(earning_below_40k | started_after_2015).tail()

996     False
997     False
998     False
999     False
1000     True
dtype: bool

In [55]:
#두 boolean Series의 값 중 하나 이상이 True인 행만을 추출한다.
employees[earning_below_40k | started_after_2015].tail()

     First Name  Gender Start Date  Salary   Mgmt         Team
958      Gloria  Female 1987-10-24   39833  False  Engineering
964       Bruce    Male 1980-05-07   35802   True        Sales
967      Thomas    Male 2016-03-12  105681  False  Engineering
989      Justin     NaN 1991-02-10   38344  False        Legal
1000        NaN     NaN        NaT       0   True          NaN

### 5.3.3 Inversion with ~

In [56]:
my_series = pd.Series([True, False, True])
my_series

0     True
1    False
2     True
dtype: bool

In [58]:
#boolean Series의 값을 반전시키는 연산자는 ~이다.
~my_series

0    False
1     True
2    False
dtype: bool

In [59]:
#Salary Series중 100000미만 값을 갖는 행만을 추출
employees[employees["Salary"] < 100000].head()

  First Name  Gender Start Date  Salary  Mgmt         Team
0    Douglas    Male 1993-08-06       0  True    Marketing
1     Thomas    Male 1996-03-31   61933  True          NaN
6       Ruby  Female 1987-08-17   65476  True      Product
7        NaN  Female 2015-07-20   45906  True      Finance
8     Angela  Female 2005-11-22   95570  True  Engineering

In [60]:
#위와 동일한 행을 추출한다. 
employees[~(employees["Salary"] >= 100000)].head()

  First Name  Gender Start Date  Salary  Mgmt         Team
0    Douglas    Male 1993-08-06       0  True    Marketing
1     Thomas    Male 1996-03-31   61933  True          NaN
6       Ruby  Female 1987-08-17   65476  True      Product
7        NaN  Female 2015-07-20   45906  True      Finance
8     Angela  Female 2005-11-22   95570  True  Engineering

### 5.3.4 Methods for Booleans

pandas method로 위에서 배운 산술 구문들을 구현할 수 있다.

    employees["Team"] == "Marketing"                           employees["Team"].eq("Marketing")
    employees["Team"] != "Marketing"                           employees["Team"].ne("Marketing")
    employees["Salary"] < 100000                               employees["Salary"].lt(100000)
    employees["Salary"] <= 100000                              employees["Salary"].le(100000)
    employees["Salary"] > 100000                               employees["Salary"].gt(100000)
    employees["Salary"] >= 100000                              employees["Salary"].ge(100000)

## 5.4 Filtering by Condition

### 5.4.1 The isin Method

In [61]:
#Sales, Legal 혹은 Marketing 팀에 속하는 직원을 추출한다.
sales = employees["Team"] == "Sales"
legal = employees["Team"] == "Legal"
mktg  = employees["Team"] == "Marketing"
employees[sales | legal | mktg].head()

   First Name  Gender Start Date  Salary   Mgmt       Team
0     Douglas    Male 1993-08-06       0   True  Marketing
5      Dennis    Male 1987-04-18  115163  False      Legal
11      Julie  Female 1997-10-26  102508   True      Legal
13       Gary    Male 2008-01-27  109831  False      Sales
20       Lois     NaN 1995-04-22   64714   True      Legal

In [70]:
#위와 동일하게 filtering하지만 이 방식이 훨씬 확장성이 좋다.
#isin() method는 list, tuple, Series등 반복 가능한 요소를 인수로 받아 boolean Series를 반환하는 method이다.

all_star_teams = ["Sales", "Legal", "Marketing"]
on_all_star_teams = employees["Team"].isin(all_star_teams)
on_all_star_teams

0        True
1       False
2       False
3       False
4       False
        ...
996     False
997     False
998     False
999      True
1000    False
Name: Team, Length: 1001, dtype: bool

In [71]:
employees[on_all_star_teams].head()

   First Name  Gender Start Date  Salary   Mgmt       Team
0     Douglas    Male 1993-08-06       0   True  Marketing
5      Dennis    Male 1987-04-18  115163  False      Legal
11      Julie  Female 1997-10-26  102508   True      Legal
13       Gary    Male 2008-01-27  109831  False      Sales
20       Lois     NaN 1995-04-22   64714   True      Legal

### 5.4.2 The between Method

In [75]:
#80000이상에서 90000미만사이의 연봉을 받는 직원을 추출한다.
higher_than_80 = employees["Salary"] >= 80000
lower_than_90 = employees["Salary"] < 90000
employees[higher_than_80 & lower_than_90].head()

   First Name  Gender Start Date  Salary   Mgmt         Team
19      Donna  Female 2010-07-22   81014  False      Product
31      Joyce     NaN 2005-02-20   88657  False      Product
35    Theresa  Female 2006-10-10   85182  False        Sales
45      Roger    Male 1980-04-17   88010   True        Sales
54       Sara  Female 2007-08-15   83677  False  Engineering

In [74]:
#위와 같은 연산을 between() method로 할 수 있다.
between_80k_and_90k = employees["Salary"].between(80000, 90000)
employees[between_80k_and_90k].head()

   First Name  Gender Start Date  Salary   Mgmt         Team
19      Donna  Female 2010-07-22   81014  False      Product
31      Joyce     NaN 2005-02-20   88657  False      Product
35    Theresa  Female 2006-10-10   85182  False        Sales
45      Roger    Male 1980-04-17   88010   True        Sales
54       Sara  Female 2007-08-15   83677  False  Engineering

In [76]:
#between() method 인자에 들어가 있는 시간 사이의 행을 추출할 수 있다.
eighties_folk = employees["Start Date"].between(
    left = "1980-01-01",
    right = "1990-01-01"
)

employees[eighties_folk].head()

   First Name  Gender Start Date  Salary   Mgmt     Team
5      Dennis    Male 1987-04-18  115163  False    Legal
6        Ruby  Female 1987-08-17   65476   True  Product
10     Louise  Female 1980-08-12   63241   True      NaN
12    Brandon    Male 1980-12-01  112807   True       HR
17      Shawn    Male 1986-12-07  111737  False  Product

In [79]:
#문자 R로 시작하는 직원을 filtering한다.
#R다음 S인데, 상한을 S로 했기 때문에 R로 시작하는 직원만 filtering된다.
#만약 between("R","T")라면 R 혹은 S로 시작하는 직원에 대한 행이 추출될 수 있다.
name_starts_with_r = employees["First Name"].between("R", "S")
employees[name_starts_with_r].head()

   First Name  Gender Start Date  Salary   Mgmt          Team
6        Ruby  Female 1987-08-17   65476   True       Product
36     Rachel  Female 2009-02-16  142032  False  Business Dev
45      Roger    Male 1980-04-17   88010   True         Sales
67     Rachel  Female 1999-08-16   51178   True       Finance
78      Robin  Female 1983-06-04  114797   True         Sales

### 5.4.3 The isnull and notnull Methods

In [80]:
employees.head()

  First Name  Gender Start Date  Salary   Mgmt       Team
0    Douglas    Male 1993-08-06       0   True  Marketing
1     Thomas    Male 1996-03-31   61933   True        NaN
2      Maria  Female        NaT  130590  False    Finance
3      Jerry     NaN 2005-03-04  138705   True    Finance
4      Larry    Male 1998-01-24  101004   True         IT

In [82]:
#Team Series중에서 null값(결측값)을 갖는 행은 True로 반환한다.
employees["Team"].isnull().head()

0    False
1     True
2    False
3    False
4    False
Name: Team, dtype: bool

In [83]:
employees["Start Date"].isnull().head()

0    False
1    False
2     True
3    False
4    False
Name: Start Date, dtype: bool

In [85]:
#Team Series중에서 null값(결측값)을 갖지 않는 행은 True로 반환한다(값이 존재하는 행은 True로 표시).
employees["Team"].notnull().head()

0     True
1    False
2     True
3     True
4     True
Name: Team, dtype: bool

In [86]:
#위와 동일한 Series를 추출할 수 있다.
(~employees["Team"].isnull()).head()

0     True
1    False
2     True
3     True
4     True
Name: Team, dtype: bool

In [87]:
#Team Series의 값이 누락된 모든 직원을 추출한다.
no_team = employees["Team"].isnull()
employees[no_team].head()

   First Name  Gender Start Date  Salary   Mgmt Team
1      Thomas    Male 1996-03-31   61933   True  NaN
10     Louise  Female 1980-08-12   63241   True  NaN
23        NaN    Male 2012-06-14  125792   True  NaN
32        NaN    Male 1998-08-21  122340   True  NaN
91      James     NaN 2005-01-26  128771  False  NaN

In [88]:
#First Name이 존재하는 행만 추출한다.
has_name = employees["First Name"].notnull()
employees[has_name].tail()

    First Name Gender Start Date  Salary   Mgmt          Team
995      Henry    NaN 2014-11-23  132483  False  Distribution
996    Phillip   Male 1984-01-31   42392  False       Finance
997    Russell   Male 2013-05-20   96914  False       Product
998      Larry   Male 2013-04-20   60500  False  Business Dev
999     Albert   Male 2012-05-15  129949   True         Sales

### 5.4.4 Dealing with Null Values

In [89]:
employees = pd.read_csv(
    "employees.csv", parse_dates = ["Start Date"]
)

/var/folders/g2/m_rjbg_d4fq330k9g6z2v24m0000gn/T/ipykernel_995/3313717471.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  employees = pd.read_csv(

In [90]:
employees

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       NaN   True     Marketing
1        Thomas    Male 1996-03-31   61933.0   True           NaN
2         Maria  Female        NaT  130590.0  False       Finance
3         Jerry     NaN 2005-03-04  138705.0   True       Finance
4         Larry    Male 1998-01-24  101004.0   True            IT
...         ...     ...        ...       ...    ...           ...
996     Phillip    Male 1984-01-31   42392.0  False       Finance
997     Russell    Male 2013-05-20   96914.0  False       Product
998       Larry    Male 2013-04-20   60500.0  False  Business Dev
999      Albert    Male 2012-05-15  129949.0   True         Sales
1000        NaN     NaN        NaT       NaN    NaN           NaN

[1001 rows x 6 columns]

In [92]:
#dropna() method는 결측값을 하나라도 갖는 DataFrame 행을 제거한다.
employees.dropna()

    First Name  Gender Start Date    Salary   Mgmt          Team
4        Larry    Male 1998-01-24  101004.0   True            IT
5       Dennis    Male 1987-04-18  115163.0  False         Legal
6         Ruby  Female 1987-08-17   65476.0   True       Product
8       Angela  Female 2005-11-22   95570.0   True   Engineering
9      Frances  Female 2002-08-08  139852.0   True  Business Dev
..         ...     ...        ...       ...    ...           ...
994     George    Male 2013-06-21   98874.0   True     Marketing
996    Phillip    Male 1984-01-31   42392.0  False       Finance
997    Russell    Male 2013-05-20   96914.0  False       Product
998      Larry    Male 2013-04-20   60500.0  False  Business Dev
999     Albert    Male 2012-05-15  129949.0   True         Sales

[761 rows x 6 columns]

In [93]:
#모든 값이 누락된 행만을 제거하고 싶다면 how매개변수에 all을 전달한다.
employees.dropna(how = "all").tail()

    First Name Gender Start Date    Salary   Mgmt          Team
995      Henry    NaN 2014-11-23  132483.0  False  Distribution
996    Phillip   Male 1984-01-31   42392.0  False       Finance
997    Russell   Male 2013-05-20   96914.0  False       Product
998      Larry   Male 2013-04-20   60500.0  False  Business Dev
999     Albert   Male 2012-05-15  129949.0   True         Sales

In [94]:
#how매개변수의 기본값은 any이다.
employees.dropna(how = "any").tail()

    First Name Gender Start Date    Salary   Mgmt          Team
994     George   Male 2013-06-21   98874.0   True     Marketing
996    Phillip   Male 1984-01-31   42392.0  False       Finance
997    Russell   Male 2013-05-20   96914.0  False       Product
998      Larry   Male 2013-04-20   60500.0  False  Business Dev
999     Albert   Male 2012-05-15  129949.0   True         Sales

In [95]:
#Gender 열에 결측값이 있을 때만 그 행을 제거한다.
employees.dropna(subset = ["Gender"]).tail()

    First Name Gender Start Date    Salary   Mgmt          Team
994     George   Male 2013-06-21   98874.0   True     Marketing
996    Phillip   Male 1984-01-31   42392.0  False       Finance
997    Russell   Male 2013-05-20   96914.0  False       Product
998      Larry   Male 2013-04-20   60500.0  False  Business Dev
999     Albert   Male 2012-05-15  129949.0   True         Sales

In [96]:
#Start Date열과 Salary열 또는 두 열 모두 결측값이 있다면 그 행을 제거한다.
employees.dropna(subset = ["Start Date", "Salary"]).head()

  First Name  Gender Start Date    Salary   Mgmt     Team
1     Thomas    Male 1996-03-31   61933.0   True      NaN
3      Jerry     NaN 2005-03-04  138705.0   True  Finance
4      Larry    Male 1998-01-24  101004.0   True       IT
5     Dennis    Male 1987-04-18  115163.0  False    Legal
6       Ruby  Female 1987-08-17   65476.0   True  Product

In [98]:
#thresh매개변수는 행이 최소 몇 개의 결측값이 아닌 값을 가져야 하는지 결정하는 임계값을 의미한다.
#이때는 결측값이 아닌 값이 최소 4개 이상 존재하는 행만을 추출한다.
employees.dropna(thresh = 4).head()

  First Name  Gender Start Date    Salary   Mgmt       Team
0    Douglas    Male 1993-08-06       NaN   True  Marketing
1     Thomas    Male 1996-03-31   61933.0   True        NaN
2      Maria  Female        NaT  130590.0  False    Finance
3      Jerry     NaN 2005-03-04  138705.0   True    Finance
4      Larry    Male 1998-01-24  101004.0   True         IT

## 5.5 Dealing with Duplicates

### 5.5.1 The duplicated Method

In [99]:
employees["Team"].head()

0    Marketing
1          NaN
2      Finance
3      Finance
4           IT
Name: Team, dtype: object

In [101]:
#duplicated() method는 열에서 중복값을 식별하는 boolean Series를 반환한다.
#Team Series를 순회하면서 이전에 한번이라도 본 적이 있는 값이라면 True를 반환한다.
employees["Team"].duplicated().head()

0    False
1    False
2    False
3     True
4    False
Name: Team, dtype: bool

In [103]:
#keep매개변수는 유지할 중복값의 위치를 나타낸다.
#first는 중복값이 첫 번째로 나타난 index를 False로 표시하여 값을 유지한다.

employees["Team"].duplicated(keep = "first").head()

0    False
1    False
2    False
3     True
4    False
Name: Team, dtype: bool

In [104]:
#last를 전달하면 마지막으로 나타나는 값을 중복되지 않은 것으로 표시한다.
employees["Team"].duplicated(keep = "last")

0        True
1        True
2        True
3        True
4        True
        ...
996     False
997     False
998     False
999     False
1000    False
Name: Team, Length: 1001, dtype: bool

In [105]:
#중복값이 첫 번째로 나타난 index만 True로 표시한다.
(~employees["Team"].duplicated()).head()

0     True
1     True
2     True
3    False
4     True
Name: Team, dtype: bool

In [107]:
#각 팀당 한 명의 직원만을 추출한다.
first_one_in_team = ~employees["Team"].duplicated()
employees[first_one_in_team]

   First Name  Gender Start Date    Salary   Mgmt          Team
0     Douglas    Male 1993-08-06       NaN   True     Marketing
1      Thomas    Male 1996-03-31   61933.0   True           NaN
2       Maria  Female        NaT  130590.0  False       Finance
4       Larry    Male 1998-01-24  101004.0   True            IT
5      Dennis    Male 1987-04-18  115163.0  False         Legal
6        Ruby  Female 1987-08-17   65476.0   True       Product
8      Angela  Female 2005-11-22   95570.0   True   Engineering
9     Frances  Female 2002-08-08  139852.0   True  Business Dev
12    Brandon    Male 1980-12-01  112807.0   True            HR
13       Gary    Male 2008-01-27  109831.0  False         Sales
40    Michael    Male 2008-10-10   99283.0   True  Distribution

### 5.5.2 The drop_duplicates Method

In [108]:
#drop_duplicates() method는 행의 모든 값이 일치하는 행을 제거한다.
employees.drop_duplicates()

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       NaN   True     Marketing
1        Thomas    Male 1996-03-31   61933.0   True           NaN
2         Maria  Female        NaT  130590.0  False       Finance
3         Jerry     NaN 2005-03-04  138705.0   True       Finance
4         Larry    Male 1998-01-24  101004.0   True            IT
...         ...     ...        ...       ...    ...           ...
996     Phillip    Male 1984-01-31   42392.0  False       Finance
997     Russell    Male 2013-05-20   96914.0  False       Product
998       Larry    Male 2013-04-20   60500.0  False  Business Dev
999      Albert    Male 2012-05-15  129949.0   True         Sales
1000        NaN     NaN        NaT       NaN    NaN           NaN

[1001 rows x 6 columns]

In [111]:
#subset매개변수에 고유값을 가져야 하는 열 목록을 전달하면 특정 열에 대한 중복을 제거할 수 있다.
#이때는 Team열 중 중복을 제거한 DataFrame을 표현한다.
employees.drop_duplicates(subset = ["Team"])

   First Name  Gender Start Date    Salary   Mgmt          Team
0     Douglas    Male 1993-08-06       NaN   True     Marketing
1      Thomas    Male 1996-03-31   61933.0   True           NaN
2       Maria  Female        NaT  130590.0  False       Finance
4       Larry    Male 1998-01-24  101004.0   True            IT
5      Dennis    Male 1987-04-18  115163.0  False         Legal
6        Ruby  Female 1987-08-17   65476.0   True       Product
8      Angela  Female 2005-11-22   95570.0   True   Engineering
9     Frances  Female 2002-08-08  139852.0   True  Business Dev
12    Brandon    Male 1980-12-01  112807.0   True            HR
13       Gary    Male 2008-01-27  109831.0  False         Sales
40    Michael    Male 2008-10-10   99283.0   True  Distribution

In [115]:
#keep에 last를 전달하여 각 중복값이 마지막으로 나타난 행을 유지한다.
#즉 팀에서 마지막으로 들어온 팀원만을 살려둔다.
employees.drop_duplicates(subset = ["Team"], keep = "last")

     First Name  Gender Start Date    Salary   Mgmt          Team
988       Alice  Female 2004-10-05   47638.0  False            HR
989      Justin     NaN 1991-02-10   38344.0  False         Legal
990       Robin  Female 1987-07-24  100765.0   True            IT
993        Tina  Female 1997-05-15   56450.0   True   Engineering
994      George    Male 2013-06-21   98874.0   True     Marketing
995       Henry     NaN 2014-11-23  132483.0  False  Distribution
996     Phillip    Male 1984-01-31   42392.0  False       Finance
997     Russell    Male 2013-05-20   96914.0  False       Product
998       Larry    Male 2013-04-20   60500.0  False  Business Dev
999      Albert    Male 2012-05-15  129949.0   True         Sales
1000        NaN     NaN        NaT       NaN    NaN           NaN

In [117]:
#keep에 False을 전달하여 중복값이 있는 모든 행을 제거한다.
#동명이인을 제거한다.
employees.drop_duplicates(subset = ["First Name"], keep = False)

    First Name  Gender Start Date    Salary   Mgmt          Team
5       Dennis    Male 1987-04-18  115163.0  False         Legal
8       Angela  Female 2005-11-22   95570.0   True   Engineering
33        Jean  Female 1993-12-18  119082.0  False  Business Dev
190      Carol  Female 1996-03-19   57783.0  False       Finance
291      Tammy  Female 1984-11-11  132839.0   True            IT
495     Eugene    Male 1984-05-24   81077.0  False         Sales
688      Brian    Male 2007-04-07   93901.0   True         Legal
832      Keith    Male 2003-02-12  120672.0  False         Legal
887      David    Male 2009-12-05   92242.0  False         Legal

In [135]:
#이름이 Douglas이고 성별이 Male인 모든 직원을 추출한다.
name_is_douglas = employees["First Name"] == "Douglas"
is_male = employees["Gender"] == "Male"
employees[name_is_douglas & is_male]

    First Name Gender Start Date    Salary   Mgmt         Team
0      Douglas   Male 1993-08-06       NaN   True    Marketing
217    Douglas   Male 1999-09-03   83341.0   True           IT
322    Douglas   Male 2002-01-08   41428.0  False      Product
835    Douglas   Male 2007-08-04  132175.0  False  Engineering

In [138]:
#subset에 주어진 열들을 기반으로 중복 여부를 확인하여 중복을 식별한다.
#예를 들어 First Name이 Douglas이고 Gender가 Male인 행들이 4개 있을 때 이 중 1개만 추출한다.
#First Name이 Douglas이지만 False인 행은 중복되는 행으로 보지 않는다.
employees.drop_duplicates(subset = ["Gender", "Team"]).head()

  First Name  Gender Start Date    Salary   Mgmt       Team
0    Douglas    Male 1993-08-06       NaN   True  Marketing
1     Thomas    Male 1996-03-31   61933.0   True        NaN
2      Maria  Female        NaT  130590.0  False    Finance
3      Jerry     NaN 2005-03-04  138705.0   True    Finance
4      Larry    Male 1998-01-24  101004.0   True         IT

## 5.6 Coding Challenge

### 5.6.1 Problems

### 5.6.2 Solutions

In [74]:
pd.read_csv("netflix.csv")

                      title        director date_added     type
0               Alias Grace             NaN   3-Nov-17  TV Show
1            A Patch of Fog  Michael Lennox  15-Apr-17    Movie
2                  Lunatics             NaN  19-Apr-19  TV Show
3                 Uriyadi 2     Vijay Kumar   2-Aug-19    Movie
4         Shrek the Musical     Jason Moore  29-Dec-13    Movie
...                     ...             ...        ...      ...
5832            The Pursuit     John Papola   7-Aug-19    Movie
5833       Hurricane Bianca   Matt Kugelman   1-Jan-17    Movie
5834           Amar's Hands  Khaled Youssef  26-Apr-19    Movie
5835  Bill Nye: Science Guy  Jason Sussberg  25-Apr-18    Movie
5836           Age of Glory             NaN        NaN  TV Show

[5837 rows x 4 columns]

In [75]:
netflix = pd.read_csv("netflix.csv", parse_dates = ["date_added"])

In [76]:
netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5837 non-null   object
 1   director    3936 non-null   object
 2   date_added  5195 non-null   datetime64[ns]
 3   type        5837 non-null   object
dtypes: datetime64[ns](1), object(3)
memory usage: 182.5+ KB

In [77]:
netflix.nunique()

title         5780
director      3024
date_added    1092
type             2
dtype: int64

In [78]:
netflix["type"] = netflix["type"].astype("category")

In [79]:
netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5837 non-null   object
 1   director    3936 non-null   object
 2   date_added  5195 non-null   datetime64[ns]
 3   type        5837 non-null   category
dtypes: category(1), datetime64[ns](1), object(2)
memory usage: 142.8+ KB

In [80]:
netflix[netflix["title"] == "Limitless"]

          title         director date_added     type
1559  Limitless      Neil Burger 2019-05-16    Movie
2564  Limitless              NaN 2016-07-01  TV Show
4579  Limitless  Vrinda Samartha 2019-10-01    Movie

In [81]:
directed_by_robert_rodriguez = (
    netflix["director"] == "Robert Rodriguez"
)
is_movie = netflix["type"] == "Movie"
netflix[directed_by_robert_rodriguez & is_movie]

,title,director,date_added,type
1384,Spy Kids: All the Time in the World,Robert Rodriguez,2019-02-19,Movie
1416,Spy Kids 3: Game Over,Robert Rodriguez,2019-04-01,Movie
1460,Spy Kids 2: The Island of Lost Dreams,Robert Rodriguez,2019-03-08,Movie
2890,Sin City,Robert Rodriguez,2019-10-01,Movie
3836,Shorts,Robert Rodriguez,2019-07-01,Movie
3883,Spy Kids,Robert Rodriguez,2019-04-01,Movie

In [82]:
added_on_july_31 = netflix["date_added"] == "2019-07-31"
directed_by_altman = netflix["director"] == "Robert Altman"
netflix[added_on_july_31 | directed_by_altman]

                                title       director date_added     type
611                            Popeye  Robert Altman 2019-11-24    Movie
1028        The Red Sea Diving Resort    Gideon Raff 2019-07-31    Movie
1092                     Gosford Park  Robert Altman 2019-11-01    Movie
3473  Bangkok Love Stories: Innocence            NaN 2019-07-31  TV Show
5117                       Ramen Shop      Eric Khoo 2019-07-31    Movie

In [83]:
directors = ["Orson Welles", "Aditya Kripalani", "Sam Raimi"]
target_directors = netflix["director"].isin(directors)
netflix[target_directors]

                           title          director date_added   type
946                 The Stranger      Orson Welles 2018-07-19  Movie
1870                    The Gift         Sam Raimi 2019-11-20  Movie
3706                Spider-Man 3         Sam Raimi 2019-11-01  Movie
4243        Tikli and Laxmi Bomb  Aditya Kripalani 2018-08-01  Movie
4475  The Other Side of the Wind      Orson Welles 2018-11-02  Movie
5115    Tottaa Pataaka Item Maal  Aditya Kripalani 2019-06-25  Movie

In [84]:
may_movies = netflix["date_added"].between(
    "2019-05-01", "2019-06-01"
)

netflix[may_movies].head()

                   title      director date_added     type
29            Chopsticks  Sachin Yardi 2019-05-31    Movie
60        Away From Home           NaN 2019-05-08  TV Show
82   III Smoking Barrels    Sanjib Dey 2019-06-01    Movie
108            Jailbirds           NaN 2019-05-10  TV Show
124              Pegasus       Han Han 2019-05-31    Movie

In [85]:
netflix.dropna(subset = ["director"]).head()

                                title        director date_added   type
1                      A Patch of Fog  Michael Lennox 2017-04-15  Movie
3                           Uriyadi 2     Vijay Kumar 2019-08-02  Movie
4                   Shrek the Musical     Jason Moore 2013-12-29  Movie
5                    Schubert In Love     Lars Büchel 2018-03-01  Movie
6  We Have Always Lived in the Castle   Stacie Passon 2019-09-14  Movie

In [86]:
netflix.drop_duplicates(subset = ["date_added"], keep = False)

,title,director,date_added,type
4,Shrek the Musical,Jason Moore,2013-12-29,Movie
12,Without Gorky,Cosima Spender,2017-05-31,Movie
30,Anjelah Johnson: Not Fancy,Jay Karas,2015-10-02,Movie
38,One Last Thing,Tim Rouhana,2019-08-25,Movie
70,Marvel's Iron Man & Hulk: Heroes United,Leo Riley,2014-02-16,Movie
...,...,...,...,...
5748,Menorca,John Barnard,2017-08-27,Movie
5749,Green Room,Jeremy Saulnier,2018-11-12,Movie
5788,Chris Brown: Welcome to My Life,Andrew Sandler,2017-10-07,Movie
5789,A Very Murray Christmas,Sofia Coppola,2015-12-04,Movie
5812,Little Singham in London,Prakash Satam,2019-04-22,Movie

## 5.7 Summary