## 10.1 Introducing the Data Sets

여러 table에 data를 분할했을 경우 이들 table을 서로 연결하여 table사이의 관계를 쉽게 식별할 수도 있다.

이때 수직과 수평 방향 모두에서 DataFrame을 추가, 연결, 조인, 병합 및 결합할 수 있다. 또한 DataFrame사이에 고유하고 공통 record를 식별할 수 있다.

In [1]:
import pandas as pd

In [2]:
groups1 = pd.read_csv("meetup/groups1.csv")
groups1.head()

   group_id                           name  category_id  city_id
0      6388         Alternative Health NYC           14    10001
1      6510      Alternative Energy Meetup            4    10001
2      8458              NYC Animal Rights           26    10001
3      8940  The New York City Anime Group           29    10001
4     10104             NYC Pit Bull Group           26    10001

In [3]:
groups2 = pd.read_csv("meetup/groups2.csv")
groups2.head()

,group_id,name,category_id,city_id
0,18879327,BachataMania,5,10001
1,18880221,Photoshoot Chicago - Photography and Modeling ...,27,60601
2,18880426,Chicago Adult Push / Kick Scooter Group Riding...,31,60601
3,18880495,Chicago International Soccer Club,32,60601
4,18880695,Impact.tech San Francisco Meetup,2,94101

In [5]:
#category.csv파일에서 카테고리의 정보를 확인할 수 있다.
categories = pd.read_csv("meetup/categories.csv")
categories.head()

   category_id            category_name
0            1           Arts & Culture
1            3       Cars & Motorcycles
2            4  Community & Environment
3            5                  Dancing
4            6     Education & Learning

In [7]:
pd.read_csv("meetup/cities.csv").head()

      id            city state    zip
0   7093   West New York    NJ   7093
1  10001        New York    NY  10001
2  13417  New York Mills    NY  13417
3  46312    East Chicago    IN  46312
4  56567  New York Mills    MN  56567

In [69]:
cities = pd.read_csv(
    "meetup/cities.csv", dtype = {"zip": "string"}   #zip의 datatype을 문자열로 하여 07093과 같이 정수 앞자리 0이 소실되지 않도록 한다.
)
cities.head()

      id            city state    zip
0   7093   West New York    NJ  07093
1  10001        New York    NY  10001
2  13417  New York Mills    NY  13417
3  46312    East Chicago    IN  46312
4  56567  New York Mills    MN  56567

## 10.2 Concatenating Data Sets

두 DataFrame을 결합하는 방법 중 하나는 하나의 DataFrame을 다른 DataFrame의 끝에 추가하여 결합하는 것이다.

In [10]:
#concat()는 두 DataFrame의 행을 하나의 DataFrame으로 결합하는 함수이다.
#objs매개변수는 리스트에 나타나는 순서대로 연결한다.
#이때 두 DataFrame모두 열의 이름이 같기에 DataFrame은 밑으로 추가된다.
pd.concat(objs = [groups1, groups2])

,group_id,name,category_id,city_id
0,6388,Alternative Health NYC,14,10001
1,6510,Alternative Energy Meetup,4,10001
2,8458,NYC Animal Rights,26,10001
3,8940,The New York City Anime Group,29,10001
4,10104,NYC Pit Bull Group,26,10001
...,...,...,...,...
8326,26377464,Shinect,34,94101
8327,26377698,The art of getting what you want [conference s...,14,94101
8328,26378067,Streeterville Running Group,9,60601
8329,26378128,Just Dance NYC,23,10001
8330,26378470,FREE Arabic Chicago Evanston North Burbs,31,60601

pandas는 groups1과 groups2에 동일한 index번호가 있는 것을 문제 삼지 않기에 연결된 DataFrame에 중복된 index label이 생긴다.

In [14]:
groups1.head()

   group_id                           name  category_id  city_id
0      6388         Alternative Health NYC           14    10001
1      6510      Alternative Energy Meetup            4    10001
2      8458              NYC Animal Rights           26    10001
3      8940  The New York City Anime Group           29    10001
4     10104             NYC Pit Bull Group           26    10001

In [15]:
groups2.tail()

,group_id,name,category_id,city_id
8326,26377464,Shinect,34,94101
8327,26377698,The art of getting what you want [conference s...,14,94101
8328,26378067,Streeterville Running Group,9,60601
8329,26378128,Just Dance NYC,23,10001
8330,26378470,FREE Arabic Chicago Evanston North Burbs,31,60601

In [16]:
len(groups1)

7999

In [17]:
len(groups2)

8331

In [18]:
len(groups1) + len(groups2)

16330

In [27]:
#ignore_index매개변수에 True를 전달하면 index번호의 중복을 제거한다.
pd.concat(objs = [groups1, groups2], ignore_index = True)

,group_id,name,category_id,city_id
0,6388,Alternative Health NYC,14,10001
1,6510,Alternative Energy Meetup,4,10001
2,8458,NYC Animal Rights,26,10001
3,8940,The New York City Anime Group,29,10001
4,10104,NYC Pit Bull Group,26,10001
...,...,...,...,...
16325,26377464,Shinect,34,94101
16326,26377698,The art of getting what you want [conference s...,14,94101
16327,26378067,Streeterville Running Group,9,60601
16328,26378128,Just Dance NYC,23,10001
16329,26378470,FREE Arabic Chicago Evanston North Burbs,31,60601

In [20]:
#keys매개변수에 전달된 list의 각 문자열을 objs list과 동일한 index 위치에 있는 DataFrame과 연결한다.
#이것을 통해 index도 중복되지 않게 생성하면서 각 행의 원본 Dataframe을 보존할 수 있다.
pd.concat(objs = [groups1, groups2], keys = ["G1", "G2"])

         group_id                                               name  \
G1 0         6388                             Alternative Health NYC
   1         6510                          Alternative Energy Meetup
   2         8458                                  NYC Animal Rights
   3         8940                      The New York City Anime Group
   4        10104                                 NYC Pit Bull Group
...           ...                                                ...
G2 8326  26377464                                            Shinect
   8327  26377698  The art of getting what you want [conference s...
   8328  26378067                        Streeterville Running Group
   8329  26378128                                     Just Dance NYC
   8330  26378470           FREE Arabic Chicago Evanston North Burbs

         category_id  city_id
G1 0              14    10001
   1               4    10001
   2              26    10001
   3              29    10001
   4              26    10001
...              ...      ...
G2 8326           34    94101
   8327           14    94101
   8328            9    60601
   8329           23    10001
   8330           31    60601

[16330 rows x 4 columns]

In [29]:
#MultiIndex DataFrame에서 loc접근자를 사용하여 해당 행을 추출할 수도 있다.
ex=pd.concat(objs = [groups1, groups2], keys = ["G1", "G2"])
print(type(ex))
ex.loc[("G2",8326)]

<class 'pandas.core.frame.DataFrame'>

group_id       26377464
name            Shinect
category_id          34
city_id           94101
Name: (G2, 8326), dtype: object

In [30]:
groups = pd.concat(objs = [groups1, groups2], ignore_index = True)

### 10.2.1 Missing Values in Combined DataFrames

두 DataFrame을 결합할 때 pandas는 dataset이 서로 공유하지 않는 행 label과 열 label의 교차점에 NaN을 배치한다.

In [31]:
sports_champions_A = pd.DataFrame(
    data = [
        ["New England Patriots", "Houston Astros"],
        ["Philadelphia Eagles", "Boston Red Sox"]
    ],
    columns = ["Football", "Baseball"],
    index = [2017, 2018]
)

sports_champions_A

                  Football        Baseball
2017  New England Patriots  Houston Astros
2018   Philadelphia Eagles  Boston Red Sox

In [34]:
sports_champions_B = pd.DataFrame(
    data = [
        ["New England Patriots", "St. Louis Blues"],
        ["Kansas City Chiefs", "Tampa Bay Lightning"]
    ],
    columns = ["Football", "Hockey"],
    index = [2019, 2020]
)
sports_champions_B

                  Football               Hockey
2019  New England Patriots      St. Louis Blues
2020    Kansas City Chiefs  Tampa Bay Lightning

In [35]:
pd.concat(objs = [sports_champions_A, sports_champions_B])

                  Football        Baseball               Hockey
2017  New England Patriots  Houston Astros                  NaN
2018   Philadelphia Eagles  Boston Red Sox                  NaN
2019  New England Patriots             NaN      St. Louis Blues
2020    Kansas City Chiefs             NaN  Tampa Bay Lightning

In [36]:
sports_champions_C = pd.DataFrame(
    data = [
        ["Pittsburgh Penguins", "Golden State Warriors"],
        ["Washington Capitals", "Golden State Warriors"]
    ],
    columns = ["Hockey", "Basketball"],
    index = [2017, 2018]
)
sports_champions_C

                   Hockey             Basketball
2017  Pittsburgh Penguins  Golden State Warriors
2018  Washington Capitals  Golden State Warriors

In [37]:
pd.concat(objs = [sports_champions_A, sports_champions_C])

,Football,Baseball,Hockey,Basketball
2017,New England Patriots,Houston Astros,NaN,NaN
2018,Philadelphia Eagles,Boston Red Sox,NaN,NaN
2017,NaN,NaN,Pittsburgh Penguins,Golden State Warriors
2018,NaN,NaN,Washington Capitals,Golden State Warriors

In [38]:
#concat()의 axis매개변수에 1혹은 "columns"을 전달하면 열 축에 걸쳐 DataFrame을 결합할 수 있다.
pd.concat(
    objs = [sports_champions_A, sports_champions_C], 
    axis = 1
)
pd.concat(
    objs = [sports_champions_A, sports_champions_C], axis = "columns"
)

,Football,Baseball,Hockey,Basketball
2017,New England Patriots,Houston Astros,Pittsburgh Penguins,Golden State Warriors
2018,Philadelphia Eagles,Boston Red Sox,Washington Capitals,Golden State Warriors

## 10.3 Left Joins

join연산은 논리적 기준을 적용하여 두 DataFrame 사이에 병합할 행 또는 열을 결정하여 병합한다.

left join은 한 DataFrame의 key를 사용하여 다른 DataFrame의 값을 가져온다.

left join은 기본 DataFrame과 관련된 추가 정보를 제공하는 목적으로 다른 DataFrame을 가져올 때 주로 사용한다.

In [46]:
groups.head(3)

   group_id                       name  category_id  city_id
0      6388     Alternative Health NYC           14    10001
1      6510  Alternative Energy Meetup            4    10001
2      8458          NYC Animal Rights           26    10001

In [40]:
categories.head(3)

   category_id            category_name
0            1           Arts & Culture
1            3       Cars & Motorcycles
2            4  Community & Environment

In [44]:
#merge()를 사용하여 하나의 DataFrame을 다른 DataFrame에 병합한다.
#method의 첫 번째 매개변수 right은 추가 정보를 제공할 DataFrame을 전달받는다.
#how매개변수에 join유형을 나타내는 문자열을 전달한다(이때는 left를 전달하여 left join임을 명시한다.).
#on매개변수에 일치 조건에 부합하는 열을 전달한다(DataFrame사이에 열 이름이 동일한 경우에만 사용할 수 있다.).
#이때는 groups에서 categories의 category_id값과 일치하는 값을 찾을 때마다 categories의 열을 가져온다.
#만약 categories에서 groups의 category_id를 찾지 못하면 categories에서 가져온 category_name열에 NaN값을 표시한다.
groups.merge(right=categories, how = "left", on = "category_id").head()

,group_id,name,category_id,city_id,category_name
0,6388,Alternative Health NYC,14,10001,Health & Wellbeing
1,6510,Alternative Energy Meetup,4,10001,Community & Environment
2,8458,NYC Animal Rights,26,10001,NaN
3,8940,The New York City Anime Group,29,10001,Sci-Fi & Fantasy
4,10104,NYC Pit Bull Group,26,10001,NaN

## 10.4 Inner Joins

inner join은 두 DataFrame에 모두 존재하는 값을 대상으로 DataFrame을 병합한다.

이때 한 DataFrame에만 존재하는 값은 제외된다.

In [47]:
groups.head(3)

   group_id                       name  category_id  city_id
0      6388     Alternative Health NYC           14    10001
1      6510  Alternative Energy Meetup            4    10001
2      8458          NYC Animal Rights           26    10001

In [48]:
categories.head(3)

   category_id            category_name
0            1           Arts & Culture
1            3       Cars & Motorcycles
2            4  Community & Environment

In [50]:
#groups와 categories에서 category_id열의 값이 동일한 행을 대상으로 지정한다.
groups.merge(categories, how = "inner", on = "category_id")

,group_id,name,category_id,city_id,category_name
0,6388,Alternative Health NYC,14,10001,Health & Wellbeing
1,6510,Alternative Energy Meetup,4,10001,Community & Environment
2,8940,The New York City Anime Group,29,10001,Sci-Fi & Fantasy
3,10359,NYC International Arabic Language & Culture Club,16,10001,Language & Ethnic Identity
4,12111,The New York City American Sign Language Meetu...,16,10001,Language & Ethnic Identity
...,...,...,...,...,...
8032,26374579,Digital Film Academy Production Pitch,20,10001,Movies & Film
8033,26374655,Vocabulary workhop,16,94101,Language & Ethnic Identity
8034,26377698,The art of getting what you want [conference s...,14,94101,Health & Wellbeing
8035,26378067,Streeterville Running Group,9,60601,Fitness
8036,26378128,Just Dance NYC,23,10001,Outdoors & Adventure

병합된 DataFrame은 두 DataFrame에서 값이 일치하는 category_id당 하나의 행을 생성한다.

category_id값이 14인 행은 groups에서는 870개나 되지만 categories에서는 1개밖에 없다.

이때 pandas는 groups의 870개 행을 각각 categories에 잇는 하나의 행과 쌍으로 만들어 병합된 DataFrame에는 총 870개의 행이 생성된다.

만약 ID가 14인 categories가 3개 있는 경우 pandas는 총 870*3=2610개의 행을 생성한다.

In [53]:
groups[groups["category_id"] == 14]

,group_id,name,category_id,city_id
0,6388,Alternative Health NYC,14,10001
52,54126,Energy Healers NYC,14,10001
78,67776,Flourishing Life Meetup,14,10001
121,111855,Hypnosis & NLP NYC - Update Your Brain,14,10001
136,129277,The Live Food Chicago Community,14,60601
...,...,...,...,...
16174,26291539,The Transformation Project: Collaborative Life...,14,94101
16201,26299876,"Cognitive Empathy, How To Translate Enemy Imag...",14,10001
16248,26322976,Contemplative Practices Group,14,94101
16314,26366221,The art of getting what you want: hacking fear,14,94101
16326,26377698,The art of getting what you want [conference s...,14,94101

In [54]:
categories[categories["category_id"] == 14]

   category_id       category_name
8           14  Health & Wellbeing

## 10.5 Outer Joins

outer join은 두 dataset의 모든 record를 병합한다.

In [55]:
groups.head(3)

   group_id                       name  category_id  city_id
0      6388     Alternative Health NYC           14    10001
1      6510  Alternative Energy Meetup            4    10001
2      8458          NYC Animal Rights           26    10001

In [56]:
cities.head(3)

      id            city state    zip
0   7093   West New York    NJ  07093
1  10001        New York    NY  10001
2  13417  New York Mills    NY  13417

In [58]:
#두 DataFrame사이에 열의 이름이 다른 경우 on매개변수가 아닌 다른 매개변수를 사용한다.
#left_on에는 merge를 호출하는 DataFrame의 열 이름을 전달하고
#right_on에는 right매개변수에 전달되는 DataFrame의 열 이름을 전달한다.

#pandas가 city_id와 id열 사이에서 일치하는 값을 찾으면 두 DataFrame의 열을 하나의 행으로 병합한다.
#만약 일치하지 않는다면 city_id에 NaN값을 배치한다.
groups.merge(
    right=cities, how = "outer", left_on = "city_id", right_on = "id"
)

,group_id,name,category_id,city_id,id,city,state,zip
0,19525264.0,West NY | Hoboken | Social Group 20s & 30s,31.0,7093.0,7093,West New York,NJ,07093
1,20240670.0,Nerdy NJ/NY,11.0,7093.0,7093,West New York,NJ,07093
2,20395344.0,The Founding Moms' Exchange: North Jersey,2.0,7093.0,7093,West New York,NJ,07093
3,21130076.0,West New York Playdates for little ones,25.0,7093.0,7093,West New York,NJ,07093
4,21825714.0,Women~Wellness~Wisdom,14.0,7093.0,7093,West New York,NJ,07093
...,...,...,...,...,...,...,...,...
16329,26373602.0,Earndotcom: SF's most awesome digital currency...,34.0,94101.0,94101,San Francisco,CA,94101
16330,26374655.0,Vocabulary workhop,16.0,94101.0,94101,San Francisco,CA,94101
16331,26377464.0,Shinect,34.0,94101.0,94101,San Francisco,CA,94101
16332,26377698.0,The art of getting what you want [conference s...,14.0,94101.0,94101,San Francisco,CA,94101
16333,NaN,NaN,NaN,NaN,95712,Chicago Park,CA,95712

In [60]:
#값이 어떤 DataFrame에 속하는지 식별하고 싶다면 merge()의 indicator매개변수에 True를 전달하면 된다.
#값이 groups에 속하면 left_only, cities에 속하면 right_only, 둘 다 속하면 both를 저장한다.
groups.merge(
    cities,
    how = "outer",
    left_on = "city_id",
    right_on = "id",
    indicator = True
)

,group_id,name,category_id,city_id,id,city,state,zip,_merge
0,19525264.0,West NY | Hoboken | Social Group 20s & 30s,31.0,7093.0,7093,West New York,NJ,07093,both
1,20240670.0,Nerdy NJ/NY,11.0,7093.0,7093,West New York,NJ,07093,both
2,20395344.0,The Founding Moms' Exchange: North Jersey,2.0,7093.0,7093,West New York,NJ,07093,both
3,21130076.0,West New York Playdates for little ones,25.0,7093.0,7093,West New York,NJ,07093,both
4,21825714.0,Women~Wellness~Wisdom,14.0,7093.0,7093,West New York,NJ,07093,both
...,...,...,...,...,...,...,...,...,...
16329,26373602.0,Earndotcom: SF's most awesome digital currency...,34.0,94101.0,94101,San Francisco,CA,94101,both
16330,26374655.0,Vocabulary workhop,16.0,94101.0,94101,San Francisco,CA,94101,both
16331,26377464.0,Shinect,34.0,94101.0,94101,San Francisco,CA,94101,both
16332,26377698.0,The art of getting what you want [conference s...,14.0,94101.0,94101,San Francisco,CA,94101,both
16333,NaN,NaN,NaN,NaN,95712,Chicago Park,CA,95712,right_only

In [61]:
outer_join = groups.merge(
    cities,
    how = "outer",
    left_on = "city_id",
    right_on = "id",
    indicator = True
)

#_merge열에서 값이 right_only인 행 즉 cities DataFrame에만 있는 도시 ID를 추출한다.
in_right_only = outer_join["_merge"] == "right_only"

outer_join[in_right_only].head()

,group_id,name,category_id,city_id,id,city,state,zip,_merge
8576,NaN,NaN,NaN,NaN,13417,New York Mills,NY,13417,right_only
8577,NaN,NaN,NaN,NaN,46312,East Chicago,IN,46312,right_only
8578,NaN,NaN,NaN,NaN,56567,New York Mills,MN,56567,right_only
16333,NaN,NaN,NaN,NaN,95712,Chicago Park,CA,95712,right_only

## 10.6 Merging on Index Labels

In [70]:
cities.head(3)

      id            city state    zip
0   7093   West New York    NJ  07093
1  10001        New York    NY  10001
2  13417  New York Mills    NY  13417

In [71]:
#join하려는 DataFrame이 primary key를 index에 저장하고자 할 때 그 key를 set_index()의 인자로 전달하면 된다.
#이때는 id열이 index label이 된다. 
cities = cities.set_index(keys="id")

In [72]:
cities.head(3)

                 city state    zip
id
7093    West New York    NJ  07093
10001        New York    NY  10001
13417  New York Mills    NY  13417

In [73]:
groups.head(3)

   group_id                       name  category_id  city_id
0      6388     Alternative Health NYC           14    10001
1      6510  Alternative Energy Meetup            4    10001
2      8458          NYC Animal Rights           26    10001

In [76]:
#right_index에 True를 전달하면 cities의 index label과 groups의 city_id열의 값과 일치하는 행을 조인한다.
groups.merge(
    cities,
    how = "left",
    left_on = "city_id",
    right_index = True
)

,group_id,name,category_id,city_id,city,state,zip
0,6388,Alternative Health NYC,14,10001,New York,NY,10001
1,6510,Alternative Energy Meetup,4,10001,New York,NY,10001
2,8458,NYC Animal Rights,26,10001,New York,NY,10001
3,8940,The New York City Anime Group,29,10001,New York,NY,10001
4,10104,NYC Pit Bull Group,26,10001,New York,NY,10001
...,...,...,...,...,...,...,...
16325,26377464,Shinect,34,94101,San Francisco,CA,94101
16326,26377698,The art of getting what you want [conference s...,14,94101,San Francisco,CA,94101
16327,26378067,Streeterville Running Group,9,60601,Chicago,IL,60290
16328,26378128,Just Dance NYC,23,10001,New York,NY,10001
16329,26378470,FREE Arabic Chicago Evanston North Burbs,31,60601,Chicago,IL,60290

## 10.7 Coding Challenge

In [38]:
pd.read_csv("restaurant/week_1_sales.csv").head()

   Customer ID  Food ID
0          537        9
1           97        4
2          658        1
3          202        2
4          155        9

In [39]:
week1 = pd.read_csv("restaurant/week_1_sales.csv")
week2 = pd.read_csv("restaurant/week_2_sales.csv")

In [40]:
pd.read_csv("restaurant/customers.csv", index_col = "ID").head()

   First Name Last Name  Gender  Company                     Occupation
ID
1      Joseph   Perkins    Male  Dynazzy  Community Outreach Specialist
2    Jennifer   Alvarez  Female     DabZ        Senior Quality Engineer
3       Roger     Black    Male  Tagfeed              Account Executive
4      Steven     Evans    Male     Fatz               Registered Nurse
5        Judy  Morrison  Female  Demivee                Legal Assistant

In [41]:
customers = pd.read_csv(
    "restaurant/customers.csv", index_col = "ID"
)

In [42]:
pd.read_csv("restaurant/foods.csv", index_col = "Food ID")

          Food Item  Price
Food ID
1             Sushi   3.99
2           Burrito   9.99
3              Taco   2.99
4        Quesadilla   4.25
5             Pizza   2.49
6             Pasta  13.99
7             Steak  24.99
8             Salad  11.25
9             Donut   0.99
10            Drink   1.75

In [43]:
foods = pd.read_csv("restaurant/foods.csv", index_col = "Food ID")

### 10.7.1 Problems

### 10.7.2 Solutions

In [44]:
pd.concat(objs = [week1, week2], keys = ["Week 1", "Week 2"])

            Customer ID  Food ID
Week 1 0            537        9
       1             97        4
       2            658        1
       3            202        2
       4            155        9
...                 ...      ...
Week 2 245          783       10
       246          556       10
       247          547        9
       248          252        9
       249          249        6

[500 rows x 2 columns]

In [45]:
week1.merge(
    right = week2, how = "inner", on = "Customer ID"
).head()

   Customer ID  Food ID_x  Food ID_y
0          537          9          5
1          155          9          3
2          155          1          3
3          503          5          8
4          503          5          9

In [46]:
week1.merge(
    right = week2, how = "inner", on = "Customer ID"
).drop_duplicates(subset = ["Customer ID"]).head()

   Customer ID  Food ID_x  Food ID_y
0          537          9          5
1          155          9          3
3          503          5          8
5          550          6          7
6          101          7          4

In [47]:
week1.merge(
    right = week2,
    how = "inner",
    on = ["Customer ID", "Food ID"]
)

   Customer ID  Food ID
0          304        3
1          540        3
2          937       10
3          233        3
4           21        4
5           21        4
6          922        1
7          578        5
8          578        5

In [48]:
week1.merge(
    right = week2,
    how = "outer",
    on = "Customer ID",
    indicator = True
).head()

   Customer ID  Food ID_x  Food ID_y     _merge
0          537        9.0        5.0       both
1           97        4.0        NaN  left_only
2          658        1.0        NaN  left_only
3          202        2.0        NaN  left_only
4          155        9.0        3.0       both

In [49]:
week1.merge(
    right = customers,
    how = "left",
    left_on = "Customer ID",
    right_index = True
).head()

,Customer ID,Food ID,First Name,Last Name,Gender,Company,Occupation
0,537,9,Cheryl,Carroll,Female,Zoombeat,Registered Nurse
1,97,4,Amanda,Watkins,Female,Ozu,Account Coordinator
2,658,1,Patrick,Webb,Male,Browsebug,Community Outreach Specialist
3,202,2,Louis,Campbell,Male,Rhynoodle,Account Representative III
4,155,9,Carolyn,Diaz,Female,Gigazoom,Database Administrator III

## 10.8 Summary